### ISSUE TITLE
Retire com.visualstudio.code.oss in favour of this package

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.vscodium.codium#1]
Call to @bilelmoussaoui really, but this package seems to be maintained version of `com.visualstudio.code.oss`. Could we retire the earlier version of Visual Studio Code sans Microsoft, so it doesn't get needlessly confusing.

**Comment by gbonnefille** [comment]
I think you make reference to https://github.com/flathub/com.visualstudio.code-oss

**Comment by noonsleeper** [comment]
hey guys, Can we could close this issue due to now `com.visualstudio.code.oss` is maintained again?

**Comment by Eonfge** [comment]
Fine by me, although I still think it's wasted effort to maintain different versions of the same app
