### ISSUE TITLE
Error updating: checksum failed

### ISSUE THREAD

**Issue by gloopsies** [flathub/com.vscodium.codium#100]
Doing daily update of all my apps I ran into an error with VSCodium:

```
Error: While pulling app/com.vscodium.codium/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='1ee7fe1615b44078a6e11983d5c4915cb8fbc15f4087814ea223002de5cc335d' actual='3614c4e33ddcad9c8deeef3882f03009fbccff1b3f265828e148833acb95cc42
```

`$flatpak repair`:  
```
Working on the system installation at /var/lib/flatpak
[175/299] Verifying flathub:app/com.vscodium.codium/x86_64/stable…
Object invalid: 2ccdd8729c6b11f2dc2ae16c091dda66c4cb383ba64ff64226e7faf7144b1a12.file
Commit should be marked partial: 081a0c449acf0fae60c28c6b62b0daffcc0dd434bb414dee826bffbb8e490220
Dry run: Deleting ref flathub:app/com.vscodium.codium/x86_64/stable due to invalid objects
```

System details:
OS: Fedora Silverblue 36
Flatpak version: 1.12.7
Gnome: 42
VSCodium: 1.66.2

**Comment by noonsleeper** [comment]
Hey @VodnikAngus, I'm using Silverblue as well, and I don't see this problem, this issue sounds more as a filesystem corruption than a flatpak problem.
I think that maybe remove codium and then reinstall will fix the problem, but try to run a filesystem `fsck` over your FS

**Comment by noonsleeper** [comment]
Hey, I'll close this very old issue, if the problem persists, don't hesitate and open a new issue.
