### ISSUE TITLE
C# Net Framework support (from muhammad sammy) breaks with 1.25

### ISSUE THREAD

**Issue by NetDwarf** [flathub/com.vscodium.codium#107]
Hello,

With version 1.25 they remove built-in mono and msbuilt (see [announcement)](https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md#announcements) and therefore break C# development on VSCodium.

I know that this cannot be directly addressed by VSCodium flatpak, however I don't know how to progress further. So this is mostly to gather options to fix this.

A current workaround is to downgrade to 1.24.4, if anyone else stumbled upon this issue.

**Comment by noonsleeper** [comment]
Hey @NetDwarf I think that you will need to use a SDK [see](https://github.com/flathub/com.vscodium.codium#sdks)

```
flatpak search sdk|grep -i mono
flatpak search sdk|grep -i net
```
It can show you a list of SDKs available and compatible with that. Then you can use the instructions on the readme on the previous link

**Comment by NetDwarf** [comment]
Hello, @noonsleeper thanks for the advice, however `org.freedesktop.Sdk.Extension.dotnet6` and `org.freedesktop.Sdk.Extension.mono6` are installed and passed via env variable (both work inside VSCodium terminal).

The problem is that msbuild is not part of mono extension (but dotnet, however this one is not working for the Extension) and the C# Extension for Net Framework requires it. `dotnet build <frameworkProject.sln>` works btw, but C# Extension 1.25 does not.

**Comment by noonsleeper** [comment]
I think the better is that you ask on https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6 or https://github.com/flathub/org.freedesktop.Sdk.Extension.mono6 to integrate these tools.

**Comment by NetDwarf** [comment]
There was someone quicker than me. https://github.com/flathub/org.freedesktop.Sdk.Extension.mono6/issues/6 
6 months and no response.

**Comment by noonsleeper** [comment]
@NetDwarf I think I'll close this issue because there is nothing to do with flatpak and more with upstream.
You need to see [here](https://github.com/OmniSharp/omnisharp-vscode/issues/5276)
