### ISSUE TITLE
rust-analyzer extension doesn't install correctly

### ISSUE THREAD

**Issue by dave-tucker** [flathub/com.vscodium.codium#112]
```
$ flatpak list | grep codium
VSCodium        com.vscodium.codium     1.69.0  stable  flathub system
```

On a fresh install, I go to Extensions and install [rust-analyzer](https://open-vsx.org/extension/matklad/rust-analyzer)
Once installed, I get an error on the `Output` tab which indicates that there was error `EACCESS` when trying to execute the following binary:
```
/var/home/dave/.var/app/com.vscodium.codium/config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
```

The problem is that for some reason the `x` bit isn't set:
```
ls -la /var/home/dave/.var/app/com.vscodium.codium/config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
-rw-r--r--. 1 dave dave 37482712 Jul 11 14:03 /var/home/dave/.var/app/com.vscodium.codium/config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
```

It can be worked around as follows:
```
chmod +x /var/home/dave/.var/app/com.vscodium.codium/config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
```

As this works fine with VSCodium from the RPM packages I assume this is something related to the Flatpak.

**Comment by noonsleeper** [comment]
@dave-tucker Hey, sorry for the late response.

Can You try to use the SDK version of rust-analizer?

```bash
flatpak install org.freedesktop.Sdk.Extension.rust-stable
# or 
flatpak install org.freedesktop.Sdk.Extension.rust-nightly
# then
FLATPAK_ENABLE_SDK_EXT=rust-stable flatpak run com.vscodium.codium
```

![image](https://user-images.githubusercontent.com/62183384/184224571-9087cd50-0c07-4991-952a-42bfb6056c0d.png)


And then try to use the extension again. Can you tell me if this works for your needs?

**Comment by Taza53** [comment]
Only using  `flatpak install org.freedesktop.Sdk.Extension.rust-stable` doesn't work. It's some bug, I think.

**Comment by noonsleeper** [comment]
Hey @Taza53, I test this since I started to use the same extension.
You can set this in order to make work the extension:

```
flatpak install org.freedesktop.Sdk.Extension.rust-stable
flatpak override --user --env=FLATPAK_ENABLE_SDK_EXT=rust-stable com.vscodium.codium
```
or 
```
flatpak install org.freedesktop.Sdk.Extension.rust-nightly
flatpak override --user --env=FLATPAK_ENABLE_SDK_EXT=rust-nightly com.vscodium.codium
```

After this, the SDK will always be available within the container. The extension work like a charm.

**Comment by noonsleeper** [comment]
Hey @dave-tucker, since you don't response to this in some time I'll close this issue, if the problem persist don't hesitate and open a new issue.
