### ISSUE TITLE
codium launches with different extensions when launched from the command line instead of using the .desktop file

### ISSUE THREAD

**Issue by gkiagia** [flathub/com.vscodium.codium#14]
When I launch codium with `flatpak run com.vscodium.codium`, it uses extensions from `~/.var/app/com.vscodium.codium/data/codium/extensions`

but if I launch if using the .desktop file (i.e. through the icon in gnome shell), it uses extensions from `~/.vscode-oss/extensions`

The difference seems to be made by the --command option. The desktop file calls:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/share/codium/codium --file-forwarding com.vscodium.codium --no-sandbox --unity-launch
```
This uses the `~/.vscode-oss` path for some reason.

Launching without the --command option uses `~/.var`:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --file-forwarding com.vscodium.codium --no-sandbox --unity-launch
```

**Comment by gkiagia** [comment]
Looks like codium is meant to be run through `codium.sh` in the flatpak.. I'm not exactly sure how this is defined to be the entry point in the flatpak, but what I understand is that the .desktop files come from the .deb package, which specifies a different entry point executable. 

I guess that an additional sed in the .yaml file would fix it: `sed "s|share/codium/codium|bin/codium.sh|"`

**Comment by noonsleeper** [comment]
thanks, good catch!
