### ISSUE TITLE
Remove app name from summary

### ISSUE THREAD

**Issue by razzeee** [flathub/com.vscodium.codium#144]
The summary should be brief and helpful. It also always shows up along side the app name.

So having the app name in the summary again doesn't make sense.

https://github.com/flathub/com.vscodium.codium/blob/master/com.vscodium.codium.metainfo.xml#L12

**Comment by noonsleeper** [comment]
Oh dear thanks, since I only focused on the editor, I made a grep over the incidences of "Visual Studio Code" from [this](https://github.com/flathub/com.visualstudio.code/blob/35102f6c3e92ebcda079c9c0a4eec1b3555ae157/com.visualstudio.code.metainfo.xml#L9)
I'll change the summary, thanks again

**Comment by razzeee** [comment]
Yeah, I raised that issue on their side of things too :)
