### ISSUE TITLE
Sidestep portal?

### ISSUE THREAD

**Issue by RalfJung** [flathub/com.vscodium.codium#147]
The flatpak grants full host file system access to vscodium, but still "open folder" goes through the portal infrastructure. This means that the usual way of switching between projects in vscode (Ctrl-R) doesn't work since it refers to these strange paths that the portal provides. Is there a way to disable the use of portals so that the paths can be directly accessed?

**Comment by noonsleeper** [comment]
Hi @RalfJung, can you detail this a little more? Also, screenshots will help.

**Comment by RalfJung** [comment]
When I select a folder to open in vscodium, it shows as `/run/user/1000/doc/eb0c2e67/cargo-careful`. This folder only exists for as long as that portal is active, and seems to disappear some time after closing the application.

Instead I'd like to open `/home/r/src/rust/cargo-careful` directly, without going through portals -- after all it has full host file system access (or I granted it access to `~/src/rust` specifically).

**Comment by RalfJung** [comment]
Oh it seems after setting up permissions properly, it is automatically doing that.  :) Sorry for bothering you.

**Comment by noonsleeper** [comment]
You don't bother me at all. If you have another question, don't hesitate and open an issue.
