### ISSUE TITLE
Somehow hijacks the Super+E shortcut

### ISSUE THREAD

**Issue by Gert-dev** [flathub/com.vscodium.codium#16]
I'm not sure how, but as soon as I install this flatpak, the `Super+E` shortcut spawns Visual Studio Code. Uninstalling it again fixes the problem.

I have no idea how or why this happens. I can't find any reference to this shortcut in the configuration files either. It is also somehow overriding it more globally than GNOME shell itself, since I have this shortcut bound to another application and trying to rebind it via the keyboard configuration in GNOME will simply spawn Visual Studio Code again.

This may be due to some external factor, but I'm not sure how to proceed debugging it. This does not happen with VSCodium if I install it from the AUR on Arch Linux.

**Comment by noonsleeper** [comment]
Hi, Maybe something on your gnome's keyboard shortcuts config is associated to a default editor as a flatpak?
This container doesn't add or modify any kind of shortcuts

**Comment by Gert-dev** [comment]
Thanks for your reply.

I have `Super+E` bound as custom keyboard shortcut to Nautilus in GNOME, which works fine. It only suddenly changes its behavior after installing this package through flatpak, though I understand this package shouldn't be having any such effect. I'm not sure how to proceed debugging what is the cause of this.

I already use VSCodium outside Flatpak, so it doesn't appear to be VSCodium itself that is causing the problem.

**Comment by noonsleeper** [comment]
Hi @Gert-dev I will close this issue due to a long period of non response. If you still having problems with, please don't hesitate to open a new ticket. =)

**Comment by Gert-dev** [comment]
No problem!

I ended up reverting to a build from the repositories because of other issues I have to figure out first, but intend to get back to using a flatpak at some point. I'm hoping that it will be magically fixed now, but in any case, since flatpaks don't mess with shortcuts, something else must have been to blame, so closing it is fine :slightly_smiling_face: .

**Comment by NeonMinnen** [comment]
Have the exact same issue.
