### ISSUE TITLE
Fractional Scaling using Wayland

### ISSUE THREAD

**Issue by mkronenberg** [flathub/com.vscodium.codium#162]
I would like to use Fractional Scaling with Wayland.

How do I set the Flatpak to use `--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by noonsleeper** [comment]
You can modify the desktop file and add those parameters like:

```bash
cp /var/lib/flatpak/exports/share/applications/com.vscodium.codium.desktop ~/.local/share/applications/com.vscodium.codium.desktop
sed -i 's/unity-launch/unity-launch --enable-features=UseOzonePlatform --ozone-platform=wayland/' ~/.local/share/applications/com.vscodium.codium.desktop
sed -i 's/new-window/new-window --enable-features=UseOzonePlatform --ozone-platform=wayland/' ~/.local/share/applications/com.vscodium.codium.desktop
```

**Comment by noonsleeper** [comment]
Hey @mkronenberg, since you don't response to this in some time I'll close this issue, if the problem persist don't hesitate and open a new issue.
