### ISSUE TITLE
can't write to root

### ISSUE THREAD

**Issue by gmankab** [flathub/com.vscodium.codium#166]
how to reprocuce:

1) flatpak run com.vscodium.codium /a.txt

2) press ctrl + s

3) nothing writed

my distro is endavour os

**Comment by noonsleeper** [comment]
Hi @gmankab, [/ and other directories are in the blacklist of flatpak](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) there isn't a simple way to bypass this.

**Comment by noonsleeper** [comment]
Hey @gmankab since this behaviour is by design in flatpak I can't do anything about it, I'll close this issue. If you have another problem, don't hesitate and open a new issue.
