### ISSUE TITLE
 VSCodium uses lower version of python than Code OSS.

### ISSUE THREAD

**Issue by Giger22** [flathub/com.vscodium.codium#168]
**Describe the bug**
VSCodium uses lower version of python than Code OSS.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Select default interpreter or enter interpreter path. I have the same path for Code OSS and VSCodium. In OSS I have python 3.10.9 (same as installed) and in VSCodium I have 3.10.6.

**Expected behavior**
VScodium should use the same version as VS Code/Code OSS. Note: I have this problem only on Linux not on Windows.

**Desktop (please complete the following information):**
 - OS_: Artix Linux 6.1.12
 - x86_64
 - 1.75.1.23040
 - n/a
 - Flatpak

**Comment by Giger22** [comment]
I chcecked aur version and it properly shows 3.10.9 not 3.10.6 but flatpak version still show the old version.
https://aur.archlinux.org/packages/vscodium-bin

**Comment by noonsleeper** [comment]
Hey @Giger22, I'll close this, if this persists don't hesitate and open a new issue.
