### ISSUE TITLE
Does not include command line tools

### ISSUE THREAD

**Issue by brodock** [flathub/com.vscodium.codium#17]
can't open a project from command line by typing `codium path`

**Comment by noonsleeper** [comment]
hi, I add a section on https://github.com/flathub/com.vscodium.codium#run-flatpak-codium-from-host-terminal
May be this is what you are looking for.
But if you want to know more I recommend [this](https://docs.flatpak.org/en/latest/using-flatpak.html#running-applications)

**Comment by brodock** [comment]
That worked... 
I just learned that flatpak doesn't allow it to install/symlink anything outside of it's container, so I guess that's why this package is not shipping a CLI.
