### ISSUE TITLE
Some extensions unavalible

### ISSUE THREAD

**Issue by xgqt** [flathub/com.vscodium.codium#18]
Are some extensions blocked? I tried to search for Emacs and got 0 results.
There are few avalible on visualstudio marketplace.
https://marketplace.visualstudio.com/search?term=emacs&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance

**Comment by xgqt** [comment]
I added a wrong link. That's marketplace for Visual Studio.

**Comment by xgqt** [comment]
Proper link:
https://marketplace.visualstudio.com/search?term=emacs&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by xgqt** [comment]
![image](https://user-images.githubusercontent.com/47485207/87835784-a1d85d00-c87d-11ea-8a85-19b2e4381334.png)

**Comment by noonsleeper** [comment]
Hi VSCodium doesn't use microsoft marketplace any more, [see](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace)

**Comment by xgqt** [comment]
> Hi VSCodium doesn't use microsoft marketplace any more, [see](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace)

Oh. Thanks for info!
