### ISSUE TITLE
Vscodium integraded terminal cannot allocate TTY properly

### ISSUE THREAD

**Issue by cassiofb-dev** [flathub/com.vscodium.codium#181]
Hi guys, just started using Flatpak and it's indeed amazing tool! I am having a problem with VSCodium where TTY cannot be allocated in integrated terminal so I cannot run some programs with root privileges like docker for example.

## The problem screenshot
![image](https://user-images.githubusercontent.com/61878987/230787587-0173568e-ec1b-4dbb-b398-ef378dfd24fe.png)

---

## VSCodium version
![image](https://user-images.githubusercontent.com/61878987/230787661-a332f21e-e28e-4ed2-a47f-a41595f9e4f8.png)

---

This may not be an issue related to VSCodium as there is 4 old issue yet open on flatpak [https://github.com/flatpak/flatpak/issues/3285](https://github.com/flatpak/flatpak/issues/3285). Any tips?

**Comment by cassiofb-dev** [comment]
I'm having the same problem with zsh and I tried on gnome (a lot of packages including flatpak need gnome dependencies so I just switched to it). I am using doas, is sudo a requirement in the host system?

![image](https://user-images.githubusercontent.com/61878987/231239918-f27b1390-4774-4bcf-8d9f-510f322703a0.png)

**Comment by noonsleeper** [comment]
> is sudo a requirement in the host system?

For the moment I think only sudo is supported, at least for the mainstream distros until they make the change from `sudo` to `doas`

**Comment by cassiofb-dev** [comment]
That's fine, as this fix is in flatpak itself I'm closing this as not planned.

Problem cause: https://github.com/flatpak/flatpak/issues/3285
