### ISSUE TITLE
git lfs missing

### ISSUE THREAD

**Issue by catdevnull** [flathub/com.vscodium.codium#184]
shouldn't the flatpak bundle git-lfs? otherwise, git lfs repos break in source control inside vscodium as it thinks that lfs files are modified even though they are not.

**Comment by catdevnull** [comment]
i don't agree; git lfs is used in many repos, and it just shows up with a broken view of the repo in vscodium. again: this breaks built-in functionality in vscodium, and lfs repos are fairly common.

**Comment by noonsleeper** [comment]
Then you need to ask about it on https://gitlab.com/freedesktop-sdk/freedesktop-sdk that is the base for this flatpak.

**Comment by catdevnull** [comment]
i already did: 

>Well, sounds like vscodium probably should bundle git-lfs
>
>git-lfs is not in Sdk. I'm not sure if there is sufficient demand for it to be there but it definitely can't land there during 22.08

in #freedesktop-sdk:matrix.org
