### ISSUE TITLE
VSCodium, when pinned to taskbar, uses completely different icon on startup

### ISSUE THREAD

**Issue by aitor-gomila** [flathub/com.vscodium.codium#186]
Not sure if this is VSCodium or the flatpak, but VSCodium has two different icons when I pin it to Flask: one that is higher res which just starts it, and a different, blurry icon for the window that actually opens it.

What must be causing this? Willing to create a PR ;-)

**Comment by noonsleeper** [comment]
Hi @aitor-gomila, can you post some screenshots about this? What distro, DE, are you using, also x11 or wayland?

**Comment by aitor-gomila** [comment]
Elementary OS, Pantheon with Plank, X11
