### ISSUE TITLE
SSH askpass not found

### ISSUE THREAD

**Issue by BeatLink** [flathub/com.vscodium.codium#19]
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory

**Comment by noonsleeper** [comment]
Are you try to execute ssh-askpass from your host?

/usr/bin/env -- flatpak-spawn --host ssh-askpass

**Comment by BeatLink** [comment]
No, Im trying to use the built in VCS system

**Comment by BeatLink** [comment]
> @BeatLink [flatpak vscode](https://github.com/flathub/com.visualstudio.code) has the same problem?

Incidentally, it doesnt! flatpak vscode works fine with git. The problem must be here i guess

**Comment by BeatLink** [comment]
> hey @BeatLink The base for this flatpak is freedesktop-sdk could you ask they can include ssh-askpass?

Seeing as flatpak vscode works maybe the issue is on this package?

**Comment by BeatLink** [comment]
It seems to be working for me now on vscodium too. Weird. Ill close the issue for now and reopen if i can reproduce
