### ISSUE TITLE
FLATPAK_ENABLE_SDK_EXT=node12 flatpak run com.vscodium.codium

### ISSUE THREAD

**Issue by vireakkeosokvibol** [flathub/com.vscodium.codium#2]
Is there a way to run `org.freedesktop.Sdk.Extension.*` `like com.visualstudio.code` ?

**Comment by noonsleeper** [comment]
Hi, there is a way to use more than one SDK with codium. Is documented [here](https://github.com/flathub/com.vscodium.codium/blob/master/flatpak-warning.txt)
But a tl;dr for your case
```
flatpak install flathub org.freedesktop.Sdk.Extension.node12
FLATPAK_ENABLE_SDK=node12 flatpak run com.vscodium.codium
```
I hope this helps
