### ISSUE TITLE
Copy from `$EXTRA_PATHS` into `$PATHS` to allow user defined paths

### ISSUE THREAD

**Issue by da2ce7** [flathub/com.vscodium.codium#205]
Related Issue for vscode: https://github.com/flathub/com.visualstudio.code/issues/419

**Comment by noonsleeper** [comment]
Hi @da2ce7, maybe this will fit better on https://github.com/flathub/ide-flatpak-wrapper/tree/zypak that is the wrapper of vscodium what do you think?

**Comment by noonsleeper** [comment]
@da2ce7 I will close this since it will be better to add this feature on https://github.com/flathub-infra/ide-flatpak-wrapper.

If you have any other problem, don't hesitate and open a new issue.
