### ISSUE TITLE
Shows up as generic wayland icon on task manager & can't pin the app on task manager.

### ISSUE THREAD

**Issue by rago666** [flathub/com.vscodium.codium#209]
![Screenshot_20230808_071156](https://github.com/flathub/com.vscodium.codium/assets/51720144/e63c9273-ecd6-4d65-b305-c7584e39887f)

Can't pin the app by right clicking on the task manager. Only way to pin it is to open the application manager > right click > pin to task manager. But clicking the icon will open a generic wayland windows on side. Found this 2 blogs from a kde developer regarding this. That's all, have a nice day.

[Fixing wayland taskbar icons - Nico's blog](https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/)
[The importance of window to desktop file mapping](https://nicolasfella.de/posts/importance-of-desktop-file-mapping/)

OS: Fedora 38 kde plasma(wayland)

**Comment by noonsleeper** [comment]
@rago666 thanks for the posts, I'll read for sure!, this is an old issue, I'll close this issue to track on the former one https://github.com/flathub/com.vscodium.codium/issues/149
