### ISSUE TITLE
Git: GPG failed to sign the data

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.vscodium.codium#21]
# Issue 

Seems Vscodium has issues signing git commits with local gpg keys. I tired enabling it in settings and also with the `git config --global commit.gpgsign true` (through an external/separate terminal). I tried to look at the manifest for [seahorse](https://github.com/flathub/org.gnome.seahorse.Application/blob/master/org.gnome.seahorse.Application.json), which worked to gen the key. However, it seems like there isn't an obvious permission missing. 

# Git Output (VScodium)

```
> git commit --quiet --allow-empty-message --file - -S
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by noonsleeper** [comment]
Hi, can you test this in the new version (1.49.0)?

**Comment by alexpattyn** [comment]
Hi @noonsleeper, just updated and the issues is still there.

**Comment by noonsleeper** [comment]
hi @alexpattyn, sorry for the long time that I took to response to this, I run a series of test and I found that If you override file permission to `xdg-run/gnupg:ro` your command line works like a charm but can you will confirm this?

You can use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to override this pesmission for vscodium on filesystem by adding `xdg-run/gnupg:ro`

or run this on the host terminal
```
flatpak override --user --filesystem=xdg-run/gnupg:ro com.vscodium.vscodium
```
close all your instance of vscodium and open a new one then try again `git commit --quiet --allow-empty-message --file - -S`

If you confirm that this works I'll add this exception to the build,

TIA

**Comment by alexpattyn** [comment]
Hey @noonsleeper, thanks for your help, but it seems I am still having the issues above. 

```
 git commit --quiet --allow-empty-message --file src/WaveModel.jl -S  
error: gpg failed to sign the data
fatal: failed to write commit object
```

Added the permission through flatseal:

![image](https://user-images.githubusercontent.com/28536677/93951096-66da2600-fd13-11ea-9051-47418e007508.png)


Although if I try to make a commit through the built-in source control it does have to sit and think about it for a second and then fails. While before it was instant, not sure if that helps at all.

**Comment by alexpattyn** [comment]
I can confirm that...

```
git commit --quiet --allow-empty-message --file src/WaveModel.jl -S  
```

Works outside VScode.

**Comment by alexpattyn** [comment]
@noonsleeper So it seems like it it working now :confused: ....

So let me confirm again, and then we should be able to close this issue.

**Comment by alexpattyn** [comment]
Alright, I can confirmed the commit went through and has been signed with my GPG key. :tada:

**Comment by alexpattyn** [comment]
Added this link for future reference: https://github.com/flatpak/xdg-desktop-portal/issues/178

**Comment by alexpattyn** [comment]
I think the issue may have to be re-opened....

So today when I went to make a commit on the same system it gave me the couldn't sign error. However, it worked again when I did the following:

1. Outside of VScodium, make the signed commit. 
2. In VScodium select `undo last commit`.
3. In VScodium make the commit.
4. It works now.

I am not sure while I have to initialize the commit from outside VScodium in order for it to start working. :confounded:

**Comment by alexpattyn** [comment]
I'll also add that the above only has to be done once. So if I close VScodium, I can open it again and keep making signed commits. Perhaps this is a keyring issue?

**Comment by noonsleeper** [comment]
I think this could be a problem with pinentry? In a new user session when I run on codium internal console 
```
sh-5.0$ touch somefile.txt
sh-5.0$ git add somefile.txt
sh-5.0$ git commit --quiet --allow-empty-message --file somefile.txt -S
```
pinentry ask for a passphrase to me and then proceed silently to commit the changes

**Comment by noonsleeper** [comment]
Can you try logout/login from your user session and try as my example? pinentry ask to you the passphrase?

**Comment by alexpattyn** [comment]
I didn't get asked for a pass-phrase from pinentry.

```
sh-5.0$ touch somefile.txt
sh-5.0$ git add somefile.txt
sh-5.0$ git commit --quiet --allow-empty-message --file somefile.txt -S
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by noonsleeper** [comment]
Have you a gui pinentry as pinentry-gnome3, pinentry-gtk, pinentry-gtk-2 or kde implementation?
The console version is not allowed.

**Comment by alexpattyn** [comment]
@noonsleeper sorry, I lost track of this issue. However, I use seahorse to gen the key and my system uses Fedora with gnome.

When I sign a commit outside of VScodium it doesn't ask for a pin or password. So I can login to a fresh session and just run `git commit -m "my message" -S` without issue. For some reason it doesn't work within Vscodium until I sign the first commit from outside of VS. 

So if I understand correctly, I don't use any GUI pinentry.

**Comment by stripedpajamas** [comment]
@alexpattyn I used to get the same message in non-flatpack VSCode, with non-gui pinentry. My issue was that the integrated terminal was too small. Simply making the integrated terminal larger allowed the TUI pinentry to display.

**Comment by alexpattyn** [comment]
Hey @stripedpajamas, not 100% if I the understand the issue though... So through an external terminal (like the one provided by gnome) I don't have issues signing commits, and I don't get prompted for pinentry.  Would normal behaviour for running `git commit -m "my message" -S` be for a pinentry prompt to show up?

**Comment by stripedpajamas** [comment]
I'm guessing when you do it through gnome terminal the keyring is coming into play? I'm really not sure how keyring interacts with terminal environment.

**Comment by noonsleeper** [comment]
hey @alexpattyn, the problem is still there?

**Comment by alexpattyn** [comment]
Hey @noonsleeper, it is. I recently had issues with it not working at all again, so I'll have to double check the permissions in flatseal.

**Comment by alexpattyn** [comment]
Seems it still has access to `xdg-run/gnupg:ro`, so I'll mess with it this weekend to see if I can't get it working again.

**Comment by alexpattyn** [comment]
@noonsleeper 

So the issue still seems to be upon start-up it doesn't allow for signing of commits. But as before...

1. Once logged in through gnome terminal `git commit -m "..." -S`.
2. In VScode `undo last commit`.
3. Make signed commit and it works. 

Before you brought up pin-entry. But in gnome terminal it doesn't ask me for a pin I just run `git commit -m "..." -S` and it works. I don't quite remember if I have a password on my key so I'll test it on a new key and see if I can replicate the issue.

**Comment by noonsleeper** [comment]
hey @alexpattyn any news about this issue? It fixed?

**Comment by alexpattyn** [comment]
@noonsleeper Not yet, last I checked. I can take another look soonish (most likely the week of the 15th).

**Comment by alexpattyn** [comment]
Turns outs https://github.com/flathub/com.vscodium.codium/issues/21#issuecomment-702379257 was right. Don't know why I didn't try that :facepalm:.

**Comment by alexpattyn** [comment]
^at least when I run `git commit -m "test" -S` from inside the vscodium terminal. Have to test it using the built-in source control (which is were the issue was originally).
