### ISSUE TITLE
[flatpack repo] missing window title in fedora gnome 44.3

### ISSUE THREAD

**Issue by zidni-bwi** [flathub/com.vscodium.codium#213]
I've tried reinstalling from flatpak, clearing the cache in the .var directory but the window title still doesn't appear

**Comment by zidni-bwi** [comment]
the extension has also been disabled but still

**Comment by zidni-bwi** [comment]
solved. i changed the window title style to custom. seems to be a problem with native integration

**Comment by noonsleeper** [comment]
try to run 
```
flatpak run com.vscodium.codium  --enable-features=WaylandWindowDecorations
```
Does this work?

**Comment by zidni-bwi** [comment]
> try to run
> 
> ```
> flatpak run com.vscodium.codium  --enable-features=WaylandWindowDecorations
> ```
> 
> Does this work?

it works. but after I cleared the cache in the .var directory the window title was missing again so I had to manually run --enable-features=WaylandWindowDecorations

**Comment by Fxsch** [comment]
I run GNOME too and had the same issue. I would guess that everyone using GNOME has this issue, so there should be a permanent fix. Is there a way to make it always use `--enable-features=WaylandWindowDecorations`?
