### ISSUE TITLE
Not using system cursor

### ISSUE THREAD

**Issue by Fxsch** [flathub/com.vscodium.codium#215]
VSCodium is not using the system cursor but a different one

**Comment by PgBiel** [comment]
Try this command from https://github.com/flatpak/flatpak/issues/709#issuecomment-1416710789:

`flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`

**Comment by Fxsch** [comment]
That works. A workaround like that shouldn't be needed tho.

**Comment by noonsleeper** [comment]
@PgBiel thanks again!

**Comment by Vilianexe** [comment]
> Try this command from [flatpak/flatpak#709 (comment)](https://github.com/flatpak/flatpak/issues/709#issuecomment-1416710789):
> 
> `flatpak override --user --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`

this could be put on the README to be easier to find

**Comment by Fxsch** [comment]
I think you shouldn't have to manually do this. This should work by default, either add this override for this application by default or fix the root of the problem.
