### ISSUE TITLE
After limiting filesystem access, shell still has full access to my home directory

### ISSUE THREAD

**Issue by leaf-node** [flathub/com.vscodium.codium#216]
Run these commands:
```
flatpak override --user com.vscodium.codium --nofilesystem=home
flatpak override --user com.vscodium.codium --filesystem=~/src
```
Then start VSCodium in the Flatpak and open a shell with `` ctrl-` ``. Then type `ls` and see all of the home files.

Expected behavior: If the shell is part of the Flatpak containerization, then it shouldn't have access to all of my files.

**Comment by PgBiel** [comment]
I believe the commands are outdated, as I think the VSCodium flatpak comes with a `host` override by default (and not `home`). Can you try replacing `home` with `host` in your first command?

**Comment by leaf-node** [comment]
Yes, that works. Thank you. : )

**Comment by noonsleeper** [comment]
@PgBiel thanks to answer this =), I'll do a fix on the doc

**Comment by PgBiel** [comment]
Glad I could help!
