### ISSUE TITLE
How to use gnome sdk?

### ISSUE THREAD

**Issue by marc0x1** [flathub/com.vscodium.codium#218]
I'm developing an app using rust and gtk. How can i use the org.gnome.Platform runtime?

**Comment by lukas-kasticky** [comment]
…and of course the [Flatpak documentation](https://docs.flatpak.org/en/latest/manifests.html#basic-properties) is very helpful as well ^^

**Comment by noonsleeper** [comment]
Hi @marc0x1,
> I'm developing an app using rust and gtk. How can i use the org.gnome.Platform runtime?

Do you mean use it as base for your app? then as @lukas-kasticky kindly answered to you.
Or if you mean as access from codium sandbox then [this](https://docs.flatpak.org/en/latest/tips-and-tricks.html#testing-an-app-with-a-different-runtime) maybe resolve your problem

**Comment by marc0x1** [comment]
> Hi @marc0x1,
> 
> > I'm developing an app using rust and gtk. How can i use the org.gnome.Platform runtime?
> 
> Do you mean use it as base for your app? then as @lukas-kasticky kindly answered to you. Or if you mean as access from codium sandbox then [this](https://docs.flatpak.org/en/latest/tips-and-tricks.html#testing-an-app-with-a-different-runtime) maybe resolve your problem

yes, that's what i meant.
`flatpak run --runtime=org.gnome.Sdk --runtime-version=44  com.vscodium.codium`
this worked. Can it be added to env variable like the other runtimes?
