### ISSUE TITLE
ozone-platform-hint and shell issue

### ISSUE THREAD

**Issue by Extarys** [flathub/com.vscodium.codium#219]
I was on Fedora 38 KDE w/ Wayland and I don't remember having any issues, but I reinstalled the OS and switched to GNOME, and now I have 2 main problems.

The first is that I see `Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.` in the shell when starting the flatpak from the terminal.

The second is the inability to close any running commands from within vscodium's terminal.

I saw multiple issues about this, most of them are closed. There is an open one for MacOS that seems like what I'm experiencing: https://github.com/microsoft/vscode/issues/184713

When I Ctrl+C, the shell closes but not the command, so I end up with a bunch of `node` processes.

`./bashrc`:
```
...
alias codium="flatpak run com.vscodium.codium "
```

Then I run:
```sh
$ codium
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
```

Inside VSCodium:
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
And hitting Ctrl+C won't close the running command but closes the terminal instead.

VSCodium info:
```
Version: 1.81.1
Release: 23222
Commit: aef377c42cea6e9aea642829953104f07097abfa
Date: 2023-08-10T18:29:01.714Z
Electron: 22.3.18
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.12-200.fc38.x86_64
```

VSCodium settings:
```
{
    "window.titleBarStyle": "custom",

    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
      "bash": {
        "path": "/usr/bin/flatpak-spawn",
        "args": ["--host", "bash"]
      }
    },
    "workbench.colorTheme": "Default Dark Modern",
}
```

System info:
```
OS: Fedora Linux 38 (Workstation Edition)
GNOME version 44.4
Windowing system Wayland
Kernel version Linux 6.4.12-200.fc38.x86_64
```

If there is a fix somewhere, and I didn't find it, I apologize. I would appreciate any help in how I can make VSCodium work on my brand-new OS :wink: 

**EDIT**
I found https://github.com/flathub/com.visualstudio.code/issues/315#issuecomment-1181637777 
So I changed my configuration to look like
```
"terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
          "path": "/usr/bin/flatpak-spawn",
          "args": ["--env=TERM=vscode", "--host", "script", "--quiet", "/dev/null"]
        }
    },
```

And now I can cancel commands without issue.

**Comment by noonsleeper** [comment]
Hi @Extarys, there are 2 separate issues here, first the most easy to answer is:

> bash: cannot set terminal process group (-1): Inappropriate ioctl for device

This is already known [issue](https://github.com/flathub/com.vscodium.codium/issues/197) and I already made a test build that fix the problem, but I need to make an MR on https://github.com/flathub/ide-flatpak-wrapper/ to support the new syntax of zypak.

And then the other issue:

> Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.

The support of wayland is not the best for code/codium (also on electron/chromiun) and sometimes is erratic, then I add `ozone-platform-hint' to the parameters on the wrapper, but this comes with new set of problems as well. Then I'll ready thinking to revert that change and add a new section on the readme file that explain about how to go full wayland.

**Comment by comminutus** [comment]
@noonsleeper is there a way to suppress these lines?:
```
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
```
I am writing a script which relies on the output of --list-extensions and I'd like to turn this output off.

**Comment by Extarys** [comment]
@noonsleeper Thank you very much for the explanation. I'll keep my eyes open. And thanks for maintaining/helping. I've been using this flatpak for ages :laughing: 

I'll leave this open, and you can close at your discretion. Since @comminutus also replied here, I don't want to be rude.

**Comment by comminutus** [comment]
@noonsleeper I realize my question is a bit off-topic. Shall I create a separate issue?

**Comment by ccoenen** [comment]
> section on the readme file that explain about how to go full wayland.

I would appreciate that. Even if it's just a pointer to "go read that article over there".
