### ISSUE TITLE
product.json should be editable

### ISSUE THREAD

**Issue by hoshsadiq** [flathub/com.vscodium.codium#22]
hi, I'm not sure if flatpak supports making changes to files directly and surviving upgrades, but `/app/share/codium/resources/app/product.json` should be editable. Currently this is not possible in an easy manner as far as I know. It requires somehow moving the json file outside the container, edit it, put it back into the container and move it to the correct place, and even then, I'm presuming the file wouldn't survive an upgrade. It would be great to have an easier alternative.

**Comment by hoshsadiq** [comment]
Scratch that, it's not possible at all as the filesystem is read-only.

**Comment by noonsleeper** [comment]
hi @hoshsadiq I was try many things to resolve this problem but none of them are "elegant, nice or simple". I think the best is try to push something like https://github.com/flathub/com.visualstudio.code-oss/commit/f4fb6f33f410a59a04a5b564792e024b524fd2cc on https://github.com/VSCodium/vscodium directly but this may be takes some time, if you need this option now the alternative is use https://github.com/flathub/com.visualstudio.code-oss or build an extension to override the file

**Comment by hoshsadiq** [comment]
Thanks. Maybe I'm misunderstanding, isn't vscodium the same as code-oss? I thought code-oss was a previous name of.

Anyway, I'll be happy to raise this on the vscodium repo.

As an alternative, can product.js not be a link to a user editable file? Something along the lines of `~/.var/app/com.vscodium.codium/config/VSCodium/product.json`. I guess it would cause issues with upgrading and/or if a user decides to remove all their user data.

**Comment by noonsleeper** [comment]
> As an alternative, can product.js not be a link to a user editable file? Something along the lines of `~/.var/app/com.vscodium.codium/config/VSCodium/product.json`. I guess it would cause issues with upgrading and/or if a user decides to remove all their user data.

I think that the approach of https://github.com/flathub/com.visualstudio.code-oss/commit/f4fb6f33f410a59a04a5b564792e024b524fd2cc for example this allow to point to a json file with the modify vars in this example the extension gallery

**Comment by noonsleeper** [comment]
hey @hoshsadiq check this issue https://github.com/VSCodium/vscodium/issues/519

**Comment by rugk** [comment]
> I think that the approach of flathub/com.visualstudio.code-oss@f4fb6f3 for example this allow to point to a json file with the modify vars in this example the extension gallery

Yes, could not you just reuse this patch here?
It's quite convenient and [I've described here how to use it](https://github.com/flathub/com.visualstudio.code-oss/issues/11#issuecomment-782694865).

**Comment by rugk** [comment]
Upstream now has a solution: https://github.com/VSCodium/vscodium/pull/674

**Comment by noonsleeper** [comment]
> Upstream now has a solution: [VSCodium/vscodium#674](https://github.com/VSCodium/vscodium/pull/674)

Yeah, I'm waiting the next release =)

**Comment by hoshsadiq** [comment]
Nice! Forgot about this issue. It's a welcome change. Thanks to everyone who contributed :)
