### ISSUE TITLE
Bug missing top bar (incl. possible fix)

### ISSUE THREAD

**Issue by martin-v** [flathub/com.vscodium.codium#221]
Since 9491aebab1a6642b6b83286fb78a854384c89846 codium uses, as expected wayland on my system (fedora 38), but the top bars are missing. 

I digged into the problem and found a solution: adding `--enable-features=WaylandWindowDecorations` as start param, as mentioned in the [archlinux wiki](https://wiki.archlinux.org/title/wayland#Electron). Works fine on my machine, but should be tested if it causes problems on x11 based system.

**Comment by martin-v** [comment]
I use the command line, didn't look for other solutions.

**Comment by MateusRodCosta** [comment]
Add this to your settings file, should be easier:

```json
    "window.titleBarStyle": "custom",
```

**Comment by UbioZur** [comment]
Same issue here on Fedora 38 KDE, for version 1.82.0.23250

Running this command (rolling back to a previous version) works:
`sudo flatpak update --commit=20aad2933e1ae45bc1cfd8292da8e7f1f1b72e2b0070cef81fc12cfd62e07f66 com.vscodium.codium`


> Add this to your settings file, should be easier:
> 
> ```json
>     "window.titleBarStyle": "custom",
> ```
This works for me on the latest version (1.82.0.23250)

For those who are not techy though, the setting file is in:
`~/.var/app/com.vscodium.codium/config/VSCodium/User/setting.json`

However, now it does not follow my system setting as it is not the native titlebar (which is hidden on my setting by default)

**Comment by martin-v** [comment]
I used the custom titleBarStyle Option for a while, but I had several crashes, so I'm back to the command line option:
```
flatpak run com.vscodium.codium --enable-features=WaylandWindowDecorations
```
Except that it's a bit annoying to start from command line I have nothing to complain so far.

**Comment by UbioZur** [comment]
Now on flatpak version 1.84.0.23306 (still Fedora 38 KDE)

> Add this to your settings file, should be easier:
> 
> ```json
>     "window.titleBarStyle": "custom",
> ```

Just this setting does not work anymore.

I must also run with the command line :(
``` bash
flatpak run com.vscodium.codium --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
```

It doesn't work if I do not use the `ozone-platform-hint=auto`

**Comment by noonsleeper** [comment]
I'll close this because it was fixed on the latest update if you have some problem you can turn again to x11 using the [override command](https://github.com/flathub/com.vscodium.codium?tab=readme-ov-file#wayland-vs-x11)
