### ISSUE TITLE
"Vala" not in extension store

### ISSUE THREAD

**Issue by marbetschar** [flathub/com.vscodium.codium#23]
Would love to install the [Vala extension](https://marketplace.visualstudio.com/items?itemName=prince781.vala), but I can't find it in the extension store. What I'm missing here?

**Comment by noonsleeper** [comment]
Hey @marbetschar, the marketplace used by VSCodium is https://open-vsx.org.
For more information check https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
and
https://github.com/VSCodium/vscodium/issues/519

**Comment by marbetschar** [comment]
@noonsleeper thanks for the clarification! Meanwhile I was able to install the Vala extension by downloading and importing it manually. Therefore closing this issue.
