### ISSUE TITLE
FR: add vscodium-insiders

### ISSUE THREAD

**Issue by GitMensch** [flathub/com.vscodium.codium#230]
downloading from https://github.com/VSCodium/vscodium-insiders/releases

**Comment by noonsleeper** [comment]
@GitMensch I'll push a new repo for vscodium-insiders to achieve this, is a problem if a point to you as a co-maintainer to accelerate the process?

**Comment by GitMensch** [comment]
I will see if I can help. Note that I don't actually _use_ flathub, just stumbled over this "missing" when adding installation instructions for vscodium insider - and found there isn't one with flathub.
If you still think that this is helpful, then feel free to add me.

**Comment by noonsleeper** [comment]
Don't worry, it is more easily to push a package [if the developers of the app are involved](https://docs.flathub.org/docs/for-app-authors/submission/#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer), I already had flatpak codium-insiders working on my pc :smiley:

**Comment by noonsleeper** [comment]
@GitMensch now that flatpak vscodium-insiders exists, I think I'll close this =) happy hacking
