### ISSUE TITLE
UI is not scaled properly (blurred) on Gnome Wayland

### ISSUE THREAD

**Issue by G-Ray** [flathub/com.vscodium.codium#231]
The UI is blurred on a HiDPI screen on Gnome Wayland.

Using `--force-device-scale-factor=2` display a correctly scaled UI, but the window is tiny and is not resizeable.

**Comment by noonsleeper** [comment]
@G-Ray hey can you try the latest version?

**Comment by G-Ray** [comment]
> @G-Ray hey can you try whit the latest version?

The latest version scales correctly ! :tada: 
Thank you

**Comment by noonsleeper** [comment]
Then I'll close this. If you find another problem, doesn't hesitate and open a new issue.
