### ISSUE TITLE
VSCodium doesn't detect the default theme

### ISSUE THREAD

**Issue by lalincedeldeserto** [flathub/com.vscodium.codium#24]
I've installed VSCodium as a flatpak package on a Fedora 33 Workstation (with Gnome 3.38.1 as DE) and I've made a modification into the settings to automatically change the theme. 

![Schermata da 2020-10-30 21-56-18](https://user-images.githubusercontent.com/33136381/97756367-0c469d80-1afb-11eb-8faf-dc18ac182ab6.png)
I'm using Adwaita theme. The problem is, when I switch to Adwaita-dark, VSCodium doesn't detect the passage to the dark variant and stays light. I've assured myself to check if other applications based on flatpak have the same behaviour. At the moment another application suffers of that little issue, that is Skype.

I've installed other applications such as Eclipse Java, or TexMaker or again GNU Octave. If I apply the  Adwaita-dark theme these change immediately or after a restart (in case of Eclipse).

**Comment by lalincedeldeserto** [comment]
Sorry for that

**Comment by noonsleeper** [comment]
hey @lalincedeldeserto 

> Today I received some updates, including kde platform and libraries. I'm sorry, I've opened this bug report too early and I didn't think that this could be caused by some packages that were in a previous version. Everything works great now! :)

I'm glad to know that everything is fine, sorry for this late reply =)
