### ISSUE TITLE
Graphic glitch on Fedora Kinoite 38 Wayland

### ISSUE THREAD

**Issue by vireakvibol** [flathub/com.vscodium.codium#249]
Computer Specs

| Hardware/Software | Information |
| -- | -- |
| CPU | AMD Ryzen 7 3700x |
| GPU | AMD Radeon Rx 6800xt |
| Ram | DDR4 64GB |
| OS | Fedora Kinoite 38
| Display | Wayland |
| Flatpak | 1.15.4 |
| Codium | 4910a57c833d4ab8f248cea44d21cdb4552a63fa78b28ed2a39cf48ab59cfc9a |

![Screenshot_20231030_212823](https://github.com/flathub/com.vscodium.codium/assets/94353620/5a2a10a6-16b0-485f-9811-00fb0bbd8e4b)

**Comment by YO-SC** [comment]
it happened to me too

**Comment by MannuelEscalaApp** [comment]
Same here, also, AMD machine with Ubuntu 22.04.3 LTS.
![image](https://github.com/flathub/com.vscodium.codium/assets/93657724/1bf24f72-2f78-4bb5-b774-83f333901fa3)

**Comment by YO-SC** [comment]
it happens on my end too 

Fedora Linux 38 (Workstation Edition) x86_64

**Comment by carpediem29** [comment]
Same issue with Fedora 39 SilverBlue & Workstation

**Comment by diego5714** [comment]
It seem to be an issue with mesa shader compilation, but there's a workaround:

https://github.com/VSCodium/vscodium/wiki/Troubleshooting#how-do-i-fix-rendering-glitches-such-as-text-andor-the-entire-interface-not-appearing

**Comment by noonsleeper** [comment]
Thanks, @diego5714 It works like a charm!

**Comment by carpediem29** [comment]
Thanks @diego5714  . Deleting  .var/app/com.vscodium.codium/config/VSCodium/GPUCache directory solved the issue for me with the Flatpak version.
