### ISSUE TITLE
Host shell configuration isn't working for an extension.

### ISSUE THREAD

**Issue by miloskroulik** [flathub/com.vscodium.codium#25]
I've installed `rusnasonov.vscode-hugo` extension and tried to run a watch task through it, only to experience an error:

```
bash: hugo: příkaz nenalezen
The terminal process "/usr/bin/env '--', 'flatpak-spawn', '--host', 'bash', '-c', 'hugo server'" failed to launch (exit code: 127).
```

Is this supposed to be working?

**Comment by noonsleeper** [comment]
I re-think this and maybe was like this problem https://github.com/flathub/com.vscodium.codium/issues/26#issuecomment-739291303

**Comment by noonsleeper** [comment]
Hi @miloskroulik  I will close this issue due to a long period of non response. If you still having problems with, please don't hesitate to open a new ticket. =)
