### ISSUE TITLE
App does not launch properly anymore on Fedora 38 KDE X11

### ISSUE THREAD

**Issue by Mitsunee** [flathub/com.vscodium.codium#250]
Tried to do some webdev today and noticed that the application fails to render:

![VSCodium window, but it's only two grey boxes](https://ieji.de/system/media_attachments/files/111/334/724/060/337/275/small/758c8deab9f53990.png)

I had to revert back multiple versions to fix it:

![output of `flatpak remote-info --log` for vscodium. A commit id is selected to show the commit I reverted to.](https://ieji.de/system/media_attachments/files/111/335/335/080/867/321/small/88fee300ef1f534d.png)

That's commit `2761d621736a288cee5d17ab997e235683ff344da25b045a75387a3efb87f88d`.

I'm unsure what exactly is broken for me since vscode&forks don't really give any CLI output, all I can provide is that I'm on Fedora 38 KDE Spin's X11 session.

**Comment by noonsleeper** [comment]
@Mitsunee I think you need to check this #249

**Comment by salim-b** [comment]
Same on Ubuntu 22.04 with AMD Radeon rx 5700. [Deleteting the GPU cache](https://github.com/VSCodium/vscodium/wiki/Troubleshooting#how-do-i-fix-rendering-glitches-such-as-text-andor-the-entire-interface-not-appearing) helped!

**Comment by Mitsunee** [comment]
> Same on Ubuntu 22.04 with AMD Radeon rx 5700. [Deleteting the GPU cache](https://github.com/VSCodium/vscodium/wiki/Troubleshooting#how-do-i-fix-rendering-glitches-such-as-text-andor-the-entire-interface-not-appearing) helped!

Just accidentally upgraded VSCodium again today and had the same graphics issues again, tried the suggested solution and that fixed it. This seems to also be what helped in #249, so display server doesn't appear to matter, merely VSCodium failing to invalidate the old GPUCache.
