### ISSUE TITLE
Adding `host-spawn` for nicer integrated terminal experience

### ISSUE THREAD

**Issue by iro-miya** [flathub/com.vscodium.codium#255]
In order to use the integrated terminal on the host system, users have to use `flatpak-spawn`, [as explained in the README](https://github.com/flathub/com.vscodium.codium#host-shell). Currently, `flatpak-spawn` has quite a few issues, especially that it [doesn't allocate TTY properly](https://github.com/flatpak/flatpak/issues/3285) which breaks some shells. A better implementation called [`host-spawn`](https://github.com/1player/host-spawn) was made to fix these issues and it's [included by default in the VS Code Flatpak](https://github.com/flathub/com.visualstudio.code#execute-commands-in-the-host-system).

Could it also be included in this one? That would be so useful!

**Comment by larina3315** [comment]
> [doesn't allocate TTY properly](https://github.com/flatpak/flatpak/issues/3285) which breaks some shells.

I use flatpak-spawn to enter a toolbox with fish as a default shell
It sometimes glitches out but usually everything works alright

**Comment by noonsleeper** [comment]
@larina3315 there is no problem because both implementation can coexist at the same time.
