### ISSUE TITLE
how to set lua??

### ISSUE THREAD

**Issue by 00pandora00** [flathub/com.vscodium.codium#266]
help i want to set lua but i don't know how

maybe will be similar to rust?

rust example:
```
flatpak install org.freedesktop.Sdk.Extension.rust-stable
flatpak override --user --env=FLATPAK_ENABLE_SDK_EXT=rust-stable com.vscodium.codium 
```

**Comment by noonsleeper** [comment]
Hi @00pandora00, I tried to search for a LUA sdk 
```
flatpak search org.freedesktop.Sdk.Extension
```
But there isn't any.

Maybe you could ask on flathub chat about support lua?

**Comment by noonsleeper** [comment]
> i will be updating here anything that need to be informed here and not there

Let me Know if you need some help

**Comment by 00pandora00** [comment]
update: i open and "feature request" in the flatpak repo to:

https://github.com/flatpak/flatpak/issues/5622

**Comment by noonsleeper** [comment]
@00pandora00 I will close this since there is nothing to do from this side. If you have any other problem, please don't hesitate and open a new issue.
