### ISSUE TITLE
Fix login persistence on KDE ?

### ISSUE THREAD

**Issue by larina3315** [flathub/com.vscodium.codium#267]
Currently in the VSCodium flatpak, when a user logs into Github then closes the application, the login information is lost.
This happens on both GNOME and KDE in my experience, but on KDE this can be fixed via adding the following lines to the flatpak manifest .yaml file under the finish-args segment.

finish-args:
...
  - --talk-name=org.kde.kwalletd5
  - --talk-name=org.kde.KWallet.*
...

(Found in https://github.com/flathub/com.visualstudio.code/issues/350 )
(This might also prove to be of interest https://github.com/flathub/com.visualstudio.code/issues/421 )

**Comment by noonsleeper** [comment]
@larina3315 will be awesome if you make an MR for this!

**Comment by larina3315** [comment]
> @larina3315 will be awesome if you make an PR for this!

https://github.com/flathub/com.vscodium.codium/pull/271
here is a PR

**Comment by noonsleeper** [comment]
this was close by https://github.com/flathub/com.vscodium.codium/pull/271
