### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by qoijjj** [flathub/com.vscodium.codium#273]
Getting verification would allow an increased level of user trust.

https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714
https://flathub.org/apps/collection/verified/1

I believe this would require the blessing of upstream devs.

**Comment by noonsleeper** [comment]
Yes, well be good indeed, I was thinking of this since `verified thing` was mention on #flathub:matrix.org

**Comment by qoijjj** [comment]
@noonsleeper great! has an issue been opened upstream at https://github.com/VSCodium/vscodium/issues?

**Comment by noonsleeper** [comment]
> @noonsleeper great! has an issue been opened upstream at https://github.com/VSCodium/vscodium/issues?

Hi @qoijjj There is any, but eventually when I have more spare time to tackle this I'll create one =)

**Comment by qoijjj** [comment]
@noonsleeper Thanks! I'm happy to do this on your behalf if you like, as well. Let me know.

**Comment by daiyam** [comment]
They have the blue checkmark. (https://flathub.org/apps/search?q=codium)
