### ISSUE TITLE
Where to Add JSON Code for Host System Shell

### ISSUE THREAD

**Issue by ganakee** [flathub/com.vscodium.codium#274]
In the Readme the Readme offers a JSON snippet
https://github.com/flathub/com.vscodium.codium/blob/master/README.md
To make the Integrated Terminal automatically use the host system's shell,
you can add this to the settings of vscodium:

```json
  {
    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
          "path": "/usr/bin/flatpak-spawn",
          "args": ["--host", "--env=TERM=xterm-256color", "bash"]
        }
    },
  }
```

However, I cannot find where to put this code.

I did CTRL+SHIFT+P and used open settings... and then tried opening each of the JSON option such as User or Workspaces.
When I try to put the copied JSON text in, the file shows an error.

Where do I put this integration code?

**Comment by crimsonfall** [comment]
Press CTRL+SHIFT+P and type 'Open User Settings'. Choose the "Open User Settings (JSON)" option. From there you can just paste the snippet into it. 

You might already have some stuff in the settings.json file. In that case, paste everything from the snippet but the first and last brackets.

Hope that helps!

**Comment by noonsleeper** [comment]
As @crimsonfall mention, 
![image](https://github.com/flathub/com.vscodium.codium/assets/62183384/6605c400-8618-4b80-8e54-6889a1a25d9a)

**Comment by noonsleeper** [comment]
@ganakee I'll close this, if you have another question or problem don't hesitate and open a new issue.
