### ISSUE TITLE
Silently doesn't start

### ISSUE THREAD

**Issue by eternal-sorrow** [flathub/com.vscodium.codium#3]
When I enter the `flatpak run com.vscodium.codium` command, exactly nothing happens. No window appears, no logs in the terminal, no status code even. Nothing. I just see my shell prompt again without any delay.

**Comment by eternal-sorrow** [comment]
I tried to run `flatpak run --command=sh com.vscodium.codium` and descend down the shell scripts. The last thing I tried is this command (inside the flatpak shell): `ELECTRON_RUN_AS_NODE=1 zypak-wrapper /app/share/codium/codium /app/share/codium/resources/app/out/cli.js` with the same result. Without the last JS file I see the Node.js command prompt.

**Comment by noonsleeper** [comment]
Hi, may be the installation fail or an invalid object? If you run [sudo flatpak repair](https://docs.flatpak.org/en/latest/using-flatpak.html#troubleshooting)

**Comment by eternal-sorrow** [comment]
OK, I did run the repair, it found quite a lot of corrupted files actually. But, unfortunately, nothing changed for vscodum.

**Comment by noonsleeper** [comment]
Today I try to reproduce this bug on fresh installs of fedora 31/32, archlinux, ubuntu 20.04

```bash
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y com.vscodium.codium
```
then
```bash
flatpak run com.vscodium.codium
```
and
```bash
flatpak run --command=sh com.vscodium.codium
ELECTRON_RUN_AS_NODE=1 zypak-wrapper /app/share/codium/codium /app/share/codium/resources/app/out/cli.js
```
And run as expected

Could you try on other pc or distro?

**Comment by eternal-sorrow** [comment]
>Could you try on another pc or distro?

No, I cannot.

**Comment by eternal-sorrow** [comment]
Is there some way I can debug this? Silent exit does not help to determine what's the reason of this behaviour.

**Comment by joseluisq** [comment]
I got similar issue try to install from Discover KDE on my ArchLinux after installed, when I have runned it the editor window was freezed. It never started.

**Comment by noonsleeper** [comment]
Hi, @eternal-sorrow 
> Isn't flatpak supposed to be distro-agnostic?
Yes, but I try to see if the problem is related to a particular compilation/package of flatpak binary or for another particularity for example selinux, apparmor, or anything like that  

> Is there some way I can debug this? Silent exit does not help to determine what's the reason of this behaviour.

To get verbose mode of codium on flatpak try to run:
```bash
flatpak run com.vscodium.codium --verbose --log debug
```
the level of verbosity is given by `--log` parameneter
all the other options and parameters are show by cli help
```bash
flatpak run com.vscodium.codium --help
```
let me know if you could found something relevant with verbose+log

**Comment by eternal-sorrow** [comment]
>`flatpak run com.vscodium.codium --verbose --log debug`
With this I get:

```
(codium:20): Gtk-WARNING **: 19:25:16.948: cannot open display: :99.0
```

**Comment by eternal-sorrow** [comment]
>Yes, but I try to see if the problem is related to a particular compilation/package of flatpak binary or for another particularity for example selinux, apparmor, or anything like that

No, I don't have any of these.

**Comment by eternal-sorrow** [comment]
The issue was caused by the environment variable `GDK_BACKEND=wayland` exported on my system. I didn't know such variables are propagated inside the sandbox and I didn't know it affected electron apps in any way.

What gave me the hint was that GIMP from flatpak (the gtk2 application) ran successfully on my system, but `flatpak run --command=gtk3-demo org.gimp.GIMP` failed with the error as above.

In any case, the fix is `flatpak override --user com.vscodium.codium --env=GDK_BACKEND=x11`.

**Comment by e-g1gor** [comment]
I got this:

`FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/share/codium/chrome-sandbox is owned by root and has mode 4755.`
