### ISSUE TITLE
Ansible extension failing

### ISSUE THREAD

**Issue by yo8192** [flathub/com.vscodium.codium#30]
Hi, 

I run vscodium with:
`$ FLATPAK_ENABLE_SDK_EXT=node14 flatpak run com.vscodium.codium/x86_64/stable`

I can install the Ansible extension, however it seems to fail running correctly with:
`The Ansible Playbook Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

and in the Ansible Playbook Language Server Output I see:
```
[Info  - 20:20:36] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '/home/thib/.var/app/com.vscodium.codium/data/codium/extensions/vscoss.vscode-ansible-0.5.2/out/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1056:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 20:20:36] Connection to server got closed. Server will not be restarted.
```

I presume something it needs is not exposed in the flatpak container... Any idea what might cause this and how to make it work?

Thanks,
Thibault

**Comment by noonsleeper** [comment]
hey, the problem is the extension itself, I was using this for a long but now is [unmaintained](https://github.com/VSChina/vscode-ansible/commit/d6d1111f85d2605a4292cc621bef4c3118d0a032)

**Comment by yo8192** [comment]
Thanks noonsleeper, I saw it wasn't kept very up to date, but I hadn't realized it was not maintained at all anymore.  
I guess I'll have to stick to Atom for Ansible then (it has an extension which does help).
