### ISSUE TITLE
App blurry with screen scaling

### ISSUE THREAD

**Issue by zecakeh** [flathub/com.vscodium.codium#301]
Since the last update that enables Wayland by default, the whole app is blurry on my screen.

I am using Fedora 39 Silverblue (so the GNOME DE on Wayland), with a HiDPI screen and 200% scaling.

See on this screenshot that everything looks blurry (text, icons) when the image is zoomed at 100%:

![image](https://github.com/flathub/com.vscodium.codium/assets/76261501/d5c0f2ca-e85d-4980-a45d-56dca94312ca)

**Comment by noonsleeper** [comment]
@zecakeh see https://issues.chromium.org/issues/40083534 maybe you need to follow the instructions on the readme and override wayland to x11 since this is an upstream problem when they fix it will be fixed for vscodium as well.
see https://github.com/flathub/com.vscodium.codium?tab=readme-ov-file#wayland-vs-x11

**Comment by zecakeh** [comment]
It tried the instructions from the README, but the app doesn't appear when I try to launch it and there are no errors in the logs.

**Comment by noonsleeper** [comment]
try this

```bash
flatpak override --user --socket=x11 --nosocket=wayland com.vscodium.codium
flatpak run com.vscodium.codium --ozone-platform=x11 --verbose
```

this fix your problem?

**Comment by zecakeh** [comment]
Yes it does

**Comment by noonsleeper** [comment]
also you can try this (backup your overrides first since this reset all of them)?
```bash
flatpak permission-reset com.vscodium.codium
flatpak override --user --reset com.vscodium.codium
flatpak override --user --nosocket=wayland com.vscodium.codium
flatpak run com.vscodium.codium . --ozone-platform=x11 --verbose
```

**Comment by zecakeh** [comment]
It works too

**Comment by zecakeh** [comment]
Is the single dot meant to be here in the last line? It works with or without it.

**Comment by noonsleeper** [comment]
> Is the single dot meant to be here in the last line? It works with or without it.

Sorry my mistake the `.` is for the current directory, is not needed for anything :smiley: 

on the other hand, I'll add an env-var to force `--ozone-platform=x11` for those who needed like you.

**Comment by zecakeh** [comment]
I don't know if it's of any interest to you, but I have the same issue with `im.riot.Riot`, and just setting `flatpak override --user --nosocket=wayland` is enough because they set the command line flags conditionally inside the flatpak: https://github.com/flathub/im.riot.Riot/blob/master/element.sh.

**Comment by noonsleeper** [comment]
@zecakeh in a couple of hours will be available a new release that I hope will fix this problem, look at this [comment](https://github.com/flathub/com.vscodium.codium/issues/303#issuecomment-1960274425)

**Comment by zecakeh** [comment]
Works like a charm!

**Comment by noonsleeper** [comment]
@zecakeh then I will close this that is already fixed
