### ISSUE TITLE
Crash on maximizing window since last update (Fedora 39, Wayland)

### ISSUE THREAD

**Issue by Altonss** [flathub/com.vscodium.codium#302]
Seems also related to #301

**Comment by noonsleeper** [comment]
> So now it's not possible to use the custom title bar anymore ^^
You mean the `native` titlebar?

I also use Fedora 39 and Gnome 45 and also `native` and `custom` titlebar work without problems with maximize
see https://github.com/flathub/com.vscodium.codium?tab=readme-ov-file#wayland-vs-x11

maybe you need to close every instance of codium 
```bash
flatpak kill com.vscodium.codium
```
and then run 
```bash
flatpak permission-reset com.vscodium.codium
```
and then try to run again codium, if these not fix the problem you can follow the readme and override wayland to return to x11
