### ISSUE TITLE
Last update `Fix nosocket is not needed` breaks a few things.

### ISSUE THREAD

**Issue by AlirezaDastyar** [flathub/com.vscodium.codium#303]
I've just updated to the latest refresh and the [Fix nosocket is not needed](https://github.com/flathub/com.vscodium.codium/commit/def1a50b54d873b3d31ca8e6f0234a87204e9329) commit breaks a few things for me.
1. The vscodium icon is replaced with generic wayland icon
2. The global menu on KDE is not working anymore(flathub/com.vscodium.codium/issues/102 )

**Comment by AlirezaDastyar** [comment]
> @AlirezaDastyar try this
> 
> ```shell
> flatpak override --user --socket=x11 --nosocket=wayland --nosocket=fallback-x11 com.vscodium.codium
> ```
> 
> this overrides the new wayland config and relay again on xwayland. With these changes I also added a section on the readme about it https://github.com/flathub/com.vscodium.codium?tab=readme-ov-file#wayland-vs-x11

With those overrides the app does not open.
```bash
$ flatpak override --user --socket=x11 --nosocket=wayland --nosocket=fallback-x11 com.vscodium.codium
$ flatpak run com.vscodium.codium 
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
```
I'm on a wayland session btw.

**Comment by noonsleeper** [comment]
try this, clean all your overrides for codium, maybe you need to backup all of that first

```bash
flatpak permission-reset com.vscodium.codium
flatpak override --user --reset com.vscodium.codium
flatpak override --user --socket=x11 com.vscodium.codium
```

**Comment by AlirezaDastyar** [comment]
Already done the reset part but here you go:
```bash
$ flatpak permission-reset com.vscodium.codium
$ flatpak override --user --reset com.vscodium.codium
$ flatpak info --show-permissions com.vscodium.codium
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;ssh-auth;
devices=all;
features=devel;
filesystems=xdg-run/gnupg:ro;xdg-config/kdeglobals:ro;host;
persistent=.vscode-oss;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.kde.kwalletd5=talk
com.canonical.AppMenu.Registrar=talk
org.freedesktop.secrets=talk

[System Bus Policy]
org.freedesktop.login1=talk

[Environment]
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

$ flatpak override --user --socket=x11 com.vscodium.codium
$ flatpak info --show-permissions com.vscodium.codium
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;ssh-auth;
devices=all;
features=devel;
filesystems=xdg-run/gnupg:ro;xdg-config/kdeglobals:ro;host;
persistent=.vscode-oss;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
org.kde.kwalletd5=talk
com.canonical.AppMenu.Registrar=talk
org.freedesktop.secrets=talk

[System Bus Policy]
org.freedesktop.login1=talk

[Environment]
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

$ flatpak run com.vscodium.codium . --ozone-platform=x11 --verbose
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
[18 zypak-helper] Using spawn strategy test 1 as set by environment
[18:0222/193853.346455:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[18:0222/193853.346506:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.

```

**Comment by noonsleeper** [comment]
Sorry my mistake the command needs to be
```bash
flatpak permission-reset com.vscodium.codium
flatpak override --user --reset com.vscodium.codium
```
and then 
```bash
flatpak override --user --socket=x11 --nosocket=wayland com.vscodium.codium
flatpak run com.vscodium.codium --ozone-platform=x11 --verbose
```

**Comment by noonsleeper** [comment]
since `ozone-platform-hint` is in auto if detect wayland try to start always on it. But if this works, I will need to add some kind of env-var to force `--ozone-platform=x11` to those that are having problems with wayland.

**Comment by AlirezaDastyar** [comment]
That was it, now it's working as before.

**Comment by daiyam** [comment]
@noonsleeper If it's a recurrent issue, do you want to add the fix in https://github.com/VSCodium/vscodium/blob/master/docs/troubleshooting.md?

**Comment by noonsleeper** [comment]
@daiyam I was pointed to a [good solution](https://github.com/flathub/com.vscodium.codium/issues/301#issuecomment-1959894595), https://github.com/flathub/com.vscodium.codium/pull/305 this take care of the ARGS for X11 and Wayland in runtime then the only thing that the user need to do is run the override that I mention on the [README.md](https://github.com/flathub/com.vscodium.codium?tab=readme-ov-file#wayland-vs-x11) this update will be available on about ~4h more, also the build able to test for 24h using this command `flatpak install --user https://dl.flathub.org/build-repo/84888/com.vscodium.codium.flatpakref`

About your idea to add this common problems to the main documentation, I think is a [good one](https://github.com/VSCodium/vscodium/pull/1811) =).

**Comment by AlirezaDastyar** [comment]
I can confirm that after the last update the issue is resolved (for me) by disabling wayland.

**Comment by noonsleeper** [comment]
@AlirezaDastyar then I will close this. If you found any other problem, don't hesitate and open a new issue.
