### ISSUE TITLE
Dont break sandbox as default for codium

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [flathub/com.vscodium.codium#31]
Hi!

Currently codium is set to break the sandbox, thus polluting the host system with files that are generated on first run. Please set the default behavior to be sandboxed (persistent). A user can easily map this if needed. Also consider using xdg-dirs as defaults, rather than just mounting whole filesystem blindly as default.

**Comment by noonsleeper** [comment]
Hi, @k6Q28k5w5eWuRuuzTg9j7GrKCbjt7 Can you provide me with a list of those files? When I'll get some spare time from my job I'll check if that change don't break the setup for current users (MRs are wellcome)

**Comment by heipa0** [comment]
Hi, I also notices that VSCodium writes config files into the home directory which it shouldn't.

Its the folder **~/.vscode-oss/** and the file  **~/.vscode-oss/argv.json** in my case.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
@noonsleeper Removing ``--filesystem=host``` from finish-args would improve the sandbox in terms of filesystem access, and prevent all the files from being created outside the sandbox. Users can then manually add directories depending on their needs. 

A tradeoff could be to remove full filesystem access, but add some common xdg dirs, such as "Documents" etc. This will allow a user to access common directories, but prevent files to be populated outside the sandbox.

**Comment by noonsleeper** [comment]
@k6Q28k5w5eWuRuuzTg9j7GrKCbjt7, I think there is no problem to switch to `xdg dirs/sandboxed` the only requirement needed is to add in the [FAQ](https://github.com/flathub/com.vscodium.codium/blob/master/README.md) a easy way to get the old behavior.

If you are ok with this, I'll wait for your MR. =)

Cheers,

**Comment by noonsleeper** [comment]
Hey @k6Q28k5w5eWuRuuzTg9j7GrKCbjt7, I will close this issue because has many months without updates.
