### ISSUE TITLE
Primary brand colors

### ISSUE THREAD

**Issue by noonsleeper** [flathub/com.vscodium.codium#311]
@daiyam I look on flathub's website and see this marked as a `problem`

![Pasted image 1](https://github.com/flathub/com.vscodium.codium/assets/62183384/373f53eb-f0aa-443b-b154-c6352d79c763)

those refer to the flatpak docs:
- https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#has-primary-brand-colors
- https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#good-brand-colors

VSCodium/Insiders has some brand colors? If not, can you help me on this?

**Comment by noonsleeper** [comment]
BTW sorry to bother on this

**Comment by daiyam** [comment]
Seems like they want the icon of the app (the circle one with white background)

**Comment by noonsleeper** [comment]
Then I look for what hex color for the background on that icon for the `ligth` primary, but what about the dark color?

**Comment by daiyam** [comment]
The correct icon is https://github.com/VSCodium/vscodium/blob/master/src/stable/resources/linux/code.png

Oh!
[https://raw.githubusercontent.com/VSCodium/vscodium/5e26c4a9c475ebf59052c2da916b80d471af739f/icons/stable/codium_cnl.svg](https://github.com/flathub/com.vscodium.codium/blob/367390dcc7bf516a548f25605025bd0fea1b257b/com.vscodium.codium.yaml#L102C14-L102C134) is building block to build the macos and windows icons (https://github.com/VSCodium/vscodium/blob/ed0de172c4a459a3c3d3eaccb1fc34b22afdd454/icons/build_icons.sh#L41C50-L41C64)

It's already in the `.deb` at `usr/share/codium-insiders/resources/app/resources/linux/code.png`

**Comment by daiyam** [comment]
Damn! I've looked at something else... Anyway, the icons will need to be fixed.

**Comment by noonsleeper** [comment]
> The correct icon is https://github.com/VSCodium/vscodium/blob/master/src/stable/resources/linux/code.png


I'll change the icon, but is there an SVG version?

**Comment by daiyam** [comment]
> I'll change the icon, but is there an SVG version?

No. But I could make one. Is it needed?

For the brand colors, I will get back to you later.

**Comment by noonsleeper** [comment]
Not needed right now, don't worry, I'll use the icon that you already give me, that has a resolution of 1024x1024 then will be good enough.

And later I'll try to add an SVG version on vscodium repo, I don't want to give you more work on this that the needed for the colors :wink:

**Comment by daiyam** [comment]
> And later I'll try to add an SVG version on vscodium repo

Don't worry, the elements of the icons are already available at:
- https://github.com/VSCodium/icons/blob/main/templates/backgrounds/circle1/main.svg
- https://github.com/VSCodium/icons/blob/main/templates/colors/blue1/normal.conf
- https://github.com/VSCodium/icons/blob/main/templates/shapes/paulo22s/main.svg

**Comment by noonsleeper** [comment]
> > And later I'll try to add an SVG version on vscodium repo
> Don't worry, the elements of the icons are already available at:
>     * https://github.com/VSCodium/icons/blob/main/templates/backgrounds/circle1/main.svg
>     * https://github.com/VSCodium/icons/blob/main/templates/colors/blue1/normal.conf
>     * https://github.com/VSCodium/icons/blob/main/templates/shapes/paulo22s/main.svg

Very useful indeed, It took me a wile, but I built a clean replica of the png version with those assets https://github.com/VSCodium/vscodium/pull/1818 =).

**Comment by daiyam** [comment]
Ok, I've created the PR (in the right repos...) to add the "brand" colors.

**Comment by noonsleeper** [comment]
Thanks @daiyam!
