### ISSUE TITLE
After update VSCode got blurry in wayland session

### ISSUE THREAD

**Issue by marcelovbcfilho** [flathub/com.vscodium.codium#313]
After update to the latest version window became blurry for some reason, but after changing the settings throw flatseal to stop using the wayland socket and instead go directly to XWayland it stopped being blurry. My monitor is a 4k one with 200% scaling so it's not fractional which always worked for me before this update. Changing the settings to stop using wayland socket by default worked.

I'm not sure what is the root cause, but I think if it was native wayland it shouldn't be blurry when scaling, specially without fractional scaling.

Software version

```
Version: 1.86.2
Release: 24057
Commit: 27d855b2b4105a2aca2445223c8f3dc4694fbd58
Date: 2024-02-26T02:36:24.035Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.4-200.fc39.x86_64
```

System information

```
# System Details Report
---

## Report details
- **Date generated:**                              2024-02-29 13:49:54

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. PRIME X570-PRO
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 9 5950X × 32
- **Graphics:**                                    AMD Radeon™ RX 6900 XT
- **Disk Capacity:**                               2.5 TB

## Software Information:
- **Firmware Version:**                            4403
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               Not Available
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.4-200.fc39.x86_64

```

Image 1: How it started out of the box, as you can see compered to the date on the top bar VSCodium is blurry
![image](https://github.com/flathub/com.vscodium.codium/assets/51462138/d81c458f-6163-4d81-a910-48d5b994cb80)

Image 2: Settings changed using flatseal to fix
![image](https://github.com/flathub/com.vscodium.codium/assets/51462138/c4744b33-3b98-42b2-a4cd-4deab2e9444c)

Image 3: My display settings
![image](https://github.com/flathub/com.vscodium.codium/assets/51462138/dfd09493-b275-4183-9747-3e337c4f2fc8)

**Comment by noonsleeper** [comment]
Hi @marcelovbcfilho, This was already adressed here **https://github.com/flathub/com.vscodium.codium/issues/301#issuecomment-1959713743**
