### ISSUE TITLE
Does this permission override command from README do anything?

### ISSUE THREAD

**Issue by causecause1** [flathub/com.vscodium.codium#323]
[I'm talking about this part of the README file.](https://github.com/flathub/com.vscodium.codium?tab=readme-ov-file#about-the-access-to-the-host-filesystem)

The first command blocks access to **home**, but does that do anything if it already has access to **host**? Was it supposed to be `flatpak override --user com.vscodium.codium --nofilesystem=host` instead?

**Comment by causecause1** [comment]
It's already been fixed in the Insiders repository. I created the PR: https://github.com/flathub/com.vscodium.codium/pull/335 (Didn't notice it in #334, so I closed it... Oops..)

**Comment by noonsleeper** [comment]
Thanks!
