### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by Zughy** [flathub/com.vscodium.codium#328]
Hello, I've installed vscodium via flatpak and, even if my system language is Spanish (ES_es) and I have installed the Spanish Language Pack on VSCodium (and restarted the software), it keeps showing me the software in English. Any idea why?

```
zughy@pop-os:~$ flatpak config
languages: *unset* (default: es)
extra-languages: *unset*
zughy@pop-os:~$ flatpak config --user
languages: *unset* (default: es)
extra-languages: *unset*
```

**Comment by noonsleeper** [comment]
Hi have you tried `ctrl+shift+p` then `> Configure Display Language > spanish` this ask for a restart and then the language of the interface will change.

![Screenshot from 2024-05-02 02-09-04](https://github.com/flathub/com.vscodium.codium/assets/62183384/2a1ef38c-467e-4784-a56f-b28c3b80657a)

**Comment by Zughy** [comment]
Works, I don't know I remembered that the option waa in Settings. Thank you :)
