### ISSUE TITLE
Use Flatpak editor wrapper

### ISSUE THREAD

**Issue by proletarius101** [flathub/com.vscodium.codium#33]
https://github.com/flathub/com.vscodium.codium/blob/master/codium.sh looks pretty much like https://github.com/gasinvein/vscode-flatpak-wrapper to me, while the latter is well maintained by flathub. And if so, we may want to just use that wrapper, eliminate the redundancy, and handle the sdk stuff better

**Comment by noonsleeper** [comment]
have you try to integrate on vscodium's flatpak? Now I can't check this properly, but when I get any spare time for my job I'll do. Btw MRs are welcome =)
