### ISSUE TITLE
[Discussion] General question about the wrapper repo

### ISSUE THREAD

**Issue by daiyam** [flathub/com.vscodium.codium#336]
Hi @noonsleeper,

I was wondering if it would be good to move your https://github.com/noonsleeper/ide-flatpak-wrapper repo under VSCodium org and to use the `master` branch instead of `wayland-support`.
Of course, you will maintain full access to the repo.

What do you think?

**Comment by noonsleeper** [comment]
Hey @daiyam,

TL;DR: to me is a good idea and if you like that way I can move the repo to codium org without hesitation =).

Now the large explanation xD

Originally it was created to merge [PR](https://github.com/flathub-infra/ide-flatpak-wrapper/pull/23) on upstream branch zypak, but sometimes I can't wait then I use the fork until changes are merged, like in this particular case =).

Also, I was thinking to ask admins if I can be added as a maintainer on upstream.

**Comment by daiyam** [comment]
Now, I understand.
First, I will push your PR. If nothing happened, then you can move the fork.

**Comment by daiyam** [comment]
Yep. Maybe, try to reformat the ifs to match the existing format (`if []; then\n`), push it and then ask for an update.
