### ISSUE TITLE
ctrl + / (ctrl + shift + 7) to toggle comment line not working

### ISSUE THREAD

**Issue by g3blv** [flathub/com.vscodium.codium#338]
**Describe the bug**
ctrl + / (ctrl + shift + 7) to toggle comment line stopped working in version 1.86.

This works as expected in ["native" VSCodium](https://github.com/VSCodium/vscodium) with the same version as the Flatpak version of VSCodium.

The last Flatpak version (I know) this worked was:

Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-01-19T18:30:44.948Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.8.8-200.fc39.x86_64

**To Reproduce**
1. Press ctrl + /  or ctrl + shift + 7 when standing on a line

**Expected behavior**
Comment `//` would toggle.

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Architecture x86_64
 - Version 1.86.2
 - App Manager DNF
 - Sandboxed Flatpak

**Additional context**
Programming Rust.

For below version, Flatpak version is broken while "native" version works.
Version: 1.89.0
Release: 24127
Commit: 4379b66f0d4dd9881ba96fa086f387725b69a24b
Date: 2024-05-06T17:54:09.063Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.8-200.fc39.x86_64

**Comment by daiyam** [comment]
Can you verify that the language extension is running (command `Developer: Show Running Extensions`)?

**Comment by g3blv** [comment]
Do you mean the Rust language extension, `rust-analyzer`?

**Comment by daiyam** [comment]
No, the extension which provides the language so it's the `Rust` extension ;)

**Comment by g3blv** [comment]
I removed a few of the extension I don't use and now it works. Thanks!

**Comment by g3blv** [comment]
These are the extensions I see under `Developer: Show Running Extensions`
```
rust-analyzer 
Git
Emmet
CodeLLDB
Merge Conflict
GitHub
TODO Highlight v2
Node Debug Auto-attach
GitBase
```

**Comment by g3blv** [comment]
@daiyam [these](https://github.com/flathub/com.vscodium.codium/issues/338#issuecomment-2105767686) are the extension I have in version 1.85.2 where everything works. Is there something I need to change in regard to the extensions?

**Comment by noonsleeper** [comment]
This only apply to `ctrl+shift+7` because `ctrl+/` on `ansi us` keyboard distributions works as expected. I change my keyboard distribution to `iso es` to test this and is reproducible.
Can you try another IDE under flatpak that use `ctr+/` for comment lines like vscode?

**Comment by g3blv** [comment]
I changed the shortcut to `crtl+shift+7` and that works.
