### ISSUE TITLE
corrupted file / checksum error

### ISSUE THREAD

**Issue by quertrakt** [flathub/com.vscodium.codium#34]
hey there,
for a week or so now i can't install the latest vscodium update due to the following error message

> Error: While pulling app/com.vscodium.codium/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='43f6492e690d288fda4c4c83c1d99ba319f9440998b30eb827085cbf476c87cd' actual='746a1fd19fcc2e3412ba69190f2638144dab293ba51d24433d1e5b2ee20611b7'

if there is anything to do on my side, pls tell me. but i guess i got no power over checksums :)

**Comment by noonsleeper** [comment]
o/, have you try  `sudo flatpak repair` may be this repair the instalation

**Comment by quertrakt** [comment]
thx for your reply. yes i did. didn't help.
but apparently i am the only one facing this issue. so i'll opt for a removal of vscodium and a fresh reinstall.

**Comment by noonsleeper** [comment]
> thx for your reply. yes i did. didn't help.
> but apparently i am the only one facing this issue. so i'll opt for a removal of vscodium and a fresh reinstall.

Well, then I close this issue. If you still having some problems with, please don't hesitate to open a new ticket. =)
