### ISSUE TITLE
Application won't open on Fedora

### ISSUE THREAD

**Issue by Atomic310** [flathub/com.vscodium.codium#348]
I installed the latest Flatpak package on my Fedora machine. I tried uninstalling and re-installing it yet the application never opens.

**Comment by daiyam** [comment]
- Fedora version?
- Xorg or Wayland?
 
Can you try to run `codium -vvv`?

**Comment by noonsleeper** [comment]
> when I ran codium -vvv it gave me "codium not found".

Try `flatpak run com.vscodium.codium -vvv`

**Comment by Atomic310** [comment]
After running `flatpak run com.vscodium.codium -vvv` I got:
`codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
/app/share/codium/codium: --openssl-legacy-provider is not allowed in NODE_OPTIONS
`

**Comment by noonsleeper** [comment]
are you sure that flatpak (the app) is correctly?

**Comment by Atomic310** [comment]
I got:
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
/app/share/codium/codium: --openssl-legacy-provider is not allowed in NODE_OPTIONS

after running flatpak run com.vscodium.codium -vvv

**Comment by Atomic310** [comment]
I just ran sudo flatpak repair and flatpak repair --user
I also re-installed vscodium multiple times.
I then ran flatpak run com.vscodium.codium --verbose
and still got:
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
/app/share/codium/codium: --openssl-legacy-provider is not allowed in NODE_OPTIONS

**Comment by noonsleeper** [comment]
Maybe you have a broken `flatpak`, because `flatpak run com.vscodium.codium --verbose` always shows you at least the zypak debug like

```
% flatpak run com.vscodium.codium --verbose
codium-wrapper: Adding /app/tools/git-lfs/bin to PATH
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
codium-wrapper: Setting up Ruby packages
Warning: 'enable-wayland-ime' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
[18 zypak-helper] Using spawn strategy test 1 as set by environment
[18:0701/124045.336006:WARNING:wayland_object.cc(159)] Binding to gtk_shell1 version 4 but version 5 is available.
[18:0701/124045.336051:WARNING:wayland_object.cc(159)] Binding to zwp_pointer_gestures_v1 version 1 but version 3 is available.
[18:0701/124045.336073:WARNING:wayland_object.cc(159)] Binding to zwp_linux_dmabuf_v1 version 3 but version 5 is available.
[18:0701/124045.431253:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[63:0701/124045.532248:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2024-07-01T15:40:45.545Z] [File Watcher (node.js)] Request to start watching: /var/home/noons/.var/app/com.vscodium.codium/config/VSCodium/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/var/home/noons/.var/app/com.vscodium.codium/config/VSCodium/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-07-01T15:40:45.559Z] Starting VSCodium
[main 2024-07-01T15:40:45.559Z] from: /app/share/codium/resources/app
[main 2024-07-01T15:40:45.560Z] args: {
...
```

I'm using Fedora 40 on multiple machines and VMs, and I don't see any mention of that line in the about "NODE_OPTIONS" in the verbose logs.

Can you show us `flatpak override --show --user com.vscodium.codium` and `flatpak override --show --system com.vscodium.codium` outputs?

**Comment by Atomic310** [comment]
I ran `flatpak override --unset-env=NODE_OPTIONS com.vscodium.codium` and that fixed the error. It starts now!
