### ISSUE TITLE
flatpakref only includes arm7 branch

### ISSUE THREAD

**Issue by elsiehupp** [flathub/com.vscodium.codium#36]
If you try and install by clicking on the "Install" button in your web browser on, say, an amd64 computer, you will get a compatibility error. Running it in the terminal, I got the following:
```bash
$ flatpak install --from ~/Downloads/com.vscodium.codium.flatpakref
error: No such ref 'app/com.vscodium.codium/x86_64/armv7' in remote flathub
```
This appears to be because the flatpakref file includes the following line:
```flatpakref
Branch=armv7
```
For whatever reason, the way you've set things up here is generating a flatpakref that only references arm7.

However, I was able to install using the command from the README:
```bash
$ flatpak install flathub com.vscodium.codium
```

**Comment by noonsleeper** [comment]
hey @elsiehupp I check this, thanks for the issue =)

**Comment by noonsleeper** [comment]
@elsiehupp hey, I make a test and I found that this problem is based on what branch I pulled last, then now I push last master And flathub show `Branch=stable` insted of `Branch=armv7`

**Comment by elsiehupp** [comment]
It looks like you fixed it. Thanks!

**Comment by elsiehupp** [comment]
It seems to be working now!
