### ISSUE TITLE
can't input chinese

### ISSUE THREAD

**Issue by rexlevin** [flathub/com.vscodium.codium#361]
version: 1.93.1.24256
issue: can't input chinese

**Comment by noonsleeper** [comment]
Hi @rexlevin, TL;DR use flatseal to disable wayland

If you like to know more on this https://github.com/microsoft/vscode/issues/167757

**Comment by rexlevin** [comment]
> Hi @rexlevin, TL;DR use flatseal to disable wayland
> 
> If you like to know more on this [microsoft/vscode#167757](https://github.com/microsoft/vscode/issues/167757)

it works, thank you~
