### ISSUE TITLE
broken on hyprland / wayland 

### ISSUE THREAD

**Issue by acidburnmonkey** [flathub/com.vscodium.codium#362]
The application window merges with the background wallpaper when i move the mouse.
am using Fedora 40 on hyprland 
![2024-09-17-022812](https://github.com/user-attachments/assets/cde94913-0829-48c4-b202-62a2b66dce58)

**Comment by noonsleeper** [comment]
Hi @acidburnmonkey, hyperland is still beta https://github.com/hyprwm/Hyprland/releases/tag/v0.43.0 maybe is a bug on that side.

**Comment by acidburnmonkey** [comment]
is strange because other electron apps work fine on hyperland

**Comment by acidburnmonkey** [comment]
I managed to fix it by forcing gpu acceleration on flatseal + disabling wayland.
