### ISSUE TITLE
Allow use of linuxbrew via environmental variable

### ISSUE THREAD

**Issue by czhang03** [flathub/com.vscodium.codium#375]
Hi, linuxbrew is a popular way to install SDK, and is recommended by the UBlue team: https://github.com/ublue-os/bluefin/issues/576

The binary of linuxbrew is installed in `/home/linuxbrew/.linuxbrew/bin`, and the environment can be loaded via the command `/home/linuxbrew/.linuxbrew/bin/brew shellenv`. I was wondering if there is a way to introduce an environment variable like `ENABLE_BREW_SDK` to execute the command `/home/linuxbrew/.linuxbrew/bin/brew shellenv` prior to launching codium. 

The implementation should be very similar to the implementation of `FLATPAK_ENABLE_SDK_EXT`, but I cannot find where that functionality is implemented in the source code.

**Comment by noonsleeper** [comment]
Hi @czhang03,

> The implementation should be very similar to the implementation of `FLATPAK_ENABLE_SDK_EXT`, but I cannot find where that functionality is implemented in the source code.

If you like to add that functionality then you will need to go to https://github.com/flathub-infra/ide-flatpak-wrapper.git is this the main startup script use by this package to start codium

https://github.com/flathub/com.vscodium.codium/blob/27d1b63964845a7c772e987dba9fc74d7c593ca8/com.vscodium.codium.yaml#L162-L164

**Comment by noonsleeper** [comment]
@czhang03, I will close this issue since it will be implemented on https://github.com/flathub-infra/ide-flatpak-wrapper.git, If you have another problem don't hesitate and open a new issue
