### ISSUE TITLE
Giant Unreadable Patch Set

### ISSUE THREAD

**Issue by czhang03** [flathub/com.vscodium.codium#376]
Hi, 

I have noticed there is a patch set here: https://github.com/flathub/com.vscodium.codium/blob/master/patches/main.js.patch that is 4MB and basically unreadable by humans.
It is pretty concerning given that codium by default have access to the whole host file system and can execute arbitrary host command (via `host-spawn`). So I wonder if there is anyway to make this patch more readable for humans, or at least document the patch so that others can audit it.

Thanks you for your hard work!

**Comment by noonsleeper** [comment]
Hi @czhang03, If you see the patch only `Replace XDG_RUNTIME_DIR by XDG_RUNTIME_DIR/app/FLATPAK_ID` but you have a good point in that is difficult to read.

> So I wonder if there is anyway to make this patch more readable for humans, or at least document the patch so that others can audit it.

Originally this was a [sed line](https://github.com/flathub/com.vscodium.codium/commit/74f47249119a4c710dd0486d991b7651ac5e4e4b), but the flathub admins recommend avoid `sed` then a patch is created, if you find a solution to this that avoid `sed` or can shorten the patch, please create an MR that will be very useful =).

If your concern is about `host-spawn` remember, you always can do `flatpak override --user com.vscodium.codium --no-talk-name=org.freedesktop.Flatpak` to remove that feature

**Comment by daiyam** [comment]
> Originally this was a [sed line](https://github.com/flathub/com.vscodium.codium/commit/74f47249119a4c710dd0486d991b7651ac5e4e4b), but the flathub admins recommend avoid sed then a patch is created

Ok, this is new. I was wondering if I did miss this huge patch.
Can you point me to the admins message? I would like to understand why they don't like `sed`.

**Comment by noonsleeper** [comment]
> Can you point me to the admins message?

@daiyam, this is the discussion https://github.com/flathub/flathub/pull/4620#discussion_r1435154992, previous to the approval of codium-insiders, I was replacing all the sed lines for patches whenever I have some free time on both codium and codium-insiders

Like I mention before, if you have some ideas about it, feel free to point me on that direction.

**Comment by noonsleeper** [comment]
And any other solution I think will be better since now and then the builds fails because of these patch

**Comment by daiyam** [comment]
> And any other solution I think will be better since now and then the builds fails because of these patch

For sure since the patch use a compiled and minified js file. The variable names are changed at each compile.

I don't like the patch-solution because:
- firstly, it obfuscates the intended modifications, not good for security;
- finally, it needs to be updated at each version.

**Comment by daiyam** [comment]
> > Can you point me to the admins message?
> 
> @daiyam, this is the discussion [flathub/flathub#4620 (comment)](https://github.com/flathub/flathub/pull/4620#discussion_r1435154992), previous to the approval of codium-insiders, I was replacing all the sed lines for patches whenever I have some free time on both codium and codium-insiders
 
Ok the comment was `sed failure mode is unexistent which make anything hard to debug.`.
I understand. The issue if that `sed` doesn't fail if the replacement can't be applied.

> Like I mention before, if you have some ideas about it, feel free to point me on that direction.

I will look into that.

**Comment by daiyam** [comment]
I can add a patch that will modify https://github.com/microsoft/vscode/blob/4224d78a27f544e30303adc464648403b456f2b0/extensions/git/src/ipc/ipcServer.ts#L21 that will change the `join` if the env variable `process.env.FLATPAK_ID` isn't empty.

I also think that the line https://github.com/microsoft/vscode/blob/4224d78a27f544e30303adc464648403b456f2b0/src/vs/base/parts/ipc/node/ipc.net.ts#L775 need also to be patched.
The variable is used underneath to create a `.sock` as in the `git` extension...

What do you think?

**Comment by noonsleeper** [comment]
Sounds perfect, with that change I can get rid of this ugly patch. Will be good if you release this on insiders first to test?

**Comment by daiyam** [comment]
PR: https://github.com/VSCodium/vscodium/pull/2071

**Comment by noonsleeper** [comment]
Like always, thanks for your support @daiyam

**Comment by daiyam** [comment]
#39 should include the patch

**Comment by noonsleeper** [comment]
Ok with #378 merged to master, we can close this.
