### ISSUE TITLE
Removing devices=all permissions does not launch codium

### ISSUE THREAD

**Issue by rshxyz** [flathub/com.vscodium.codium#381]
if you remove the devices=all permissions codium does not launch, i don't believe this expected behaviour as visual studio code flatpak you can remove the permission and it still launches

**Comment by noonsleeper** [comment]
I can't say what visual studio support, but codium start with GPU acceleration, then as minimum is expected `device=dri`

**Comment by noonsleeper** [comment]
Maybe `--disable-gpu` disable the GPU accel, but you will experiment heavy cpu usage and performance issues since all the heavy work is doing by pure CPU.

**Comment by noonsleeper** [comment]
> Actually just clicking file with the default flatpak permissions crashes codium, thats really weird.

I recommend you look in the issues before, since this is a well known issue for 1.95
https://github.com/flathub/com.vscodium.codium/issues/380
https://github.com/flathub/com.vscodium.codium/issues/382
