### ISSUE TITLE
CLICKING "FILE" FROM THE MENU BAR AUTOMATICALLY CLOSES THE APP

### ISSUE THREAD

**Issue by ceeweb** [flathub/com.vscodium.codium#382]
1) Installed vscodium version 1.94.2.24286 as a user on my linux desktop running Pop!_OS 22.04LTS Desktop using flatpak

https://github.com/user-attachments/assets/aa886284-efaa-4087-9202-68c267946a42

2) Launched vscodium
3) Move mouse over "File" MENU BAR ITEM 
4) Click "Fifle" MENU BAR ITEM
5) The applicaiton immediately closes

I can click on and access all other Menu items with no issue.

**Comment by daiyam** [comment]
There is a bug in Electron that has the same behaviour and is affecting `1.95` (https://github.com/VSCodium/vscodium/issues/2082), maybe your issue is related.

Can you try with the setting "window.titleBarStyle": "custom"?

**Comment by ceeweb** [comment]
Perfecto! That resolved it!  I will mark this as resolved unless there is an updated that needs to be pushed in the code?
