### ISSUE TITLE
SteamDeckOS crashing

### ISSUE THREAD

**Issue by zbnewtz** [flathub/com.vscodium.codium#386]
When the file tab is clicked whatsoever, the entire application freezes and shuts down. I've downloaded this via the discover tab, and a review has stated that another user is experiencing this issue as well.

**Comment by daiyam** [comment]
I don't have a Steam Deck so I can't test it. And I don't know why it's on the discover tab...

Where can I check the page? What are the sources of the packages?

**Comment by acperkins** [comment]
This was fixed upstream in release 1.95.3. The VSCodium fix is [here](https://github.com/VSCodium/vscodium/releases/tag/1.95.3.24321).

**Comment by daiyam** [comment]
Oh! The File menu... Yep, it has been fixed.
