### ISSUE TITLE
Automatically update upon new releases

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.vscodium.codium#39]
Perhaps we want to check out https://github.com/flathub/flatpak-external-data-checker? That way PRs don't have to be manually made for every new release. Haven't used that tool before though.

**Comment by noonsleeper** [comment]
@alexpattyn Yes, I am looking for that but also I'm changing the way of make the build to a directly from the upstream instead of from deb

**Comment by alexpattyn** [comment]
Sounds good. Building directly from upstream would be preferable.

**Comment by noonsleeper** [comment]
Hey @alexpattyn, the flatpak-external-data-checker was implemented, I will close this issue. In the future, I will try to implement directly from upstream
