### ISSUE TITLE
My Vscodium application icon is missing in Ubuntu 20.04

### ISSUE THREAD

**Issue by kakashigenz** [flathub/com.vscodium.codium#396]
After i installed Vscodium by flatpak, i haven't seen the app icon

**Comment by noonsleeper** [comment]
Hi @kakashigenz are you tried `flatpak repair` or `sudo flatpak repair`?

**Comment by kakashigenz** [comment]
> Hi @kakashigenz are you tried `flatpak repair` or `sudo flatpak repair`?

Thank you, it works
