### ISSUE TITLE
Set WM_CLASS so I can use flatpak version together with other versions (snap, etc)

### ISSUE THREAD

**Issue by geekley** [flathub/com.vscodium.codium#41]
I want to use the flatpak version together with other versions of Codium (snap) without clash in taskbar icons.
However, the problem is: both versions use the same WM_CLASS (vscodium).

How can I set the WM_CLASS of flatpak codium?
Is there some command I can run in my local .desktop file like below?
```sh
Exec=some-command-change-wmclass --to=VSCodium.flatpak /usr/bin/flatpak run # args, etc...
StartupWMClass=VSCodium.flatpak
```
Or maybe some file I can change to set this in a way that persists app updates?

**Comment by noonsleeper** [comment]
Hi @geekley, I don't know how to change the WM_CLASS. You can try to make a custom `.desktop` for your needs.

**Comment by noonsleeper** [comment]
@geekley I'll close this issue. If you have another question or bug don't hesitate and open a new ticket.
