### ISSUE TITLE
Failed to find the "go" binary

### ISSUE THREAD

**Issue by grisu48** [flathub/com.vscodium.codium#44]
Hi,

when using the current flatpak version of VSCodium in conjunction with the [go extension](https://marketplace.visualstudio.com/items?itemName=golang.go), VSCodium complains that it cannot access the `go` binary, despite installed on the host system.

See the attached Screenshot (lower right corner)

![Screenshot from 2021-06-29 14-42-11](https://user-images.githubusercontent.com/1527829/123799344-6c8b1a80-d8e8-11eb-83f5-79fcbe05ec10.png)

`go` is installed via default system packages on a recent openSUSE Tumbleweed system:

    $ go version
    go version go1.16.5 linux/amd64
    $ whereis go
    go: /usr/bin/go /usr/lib64/go /usr/share/go

I understand that there are some kind of sandboxing mechanisms in place that might prevent access to system binaries?

**Comment by noonsleeper** [comment]
Hi, you can achieve this with https://github.com/flathub/com.vscodium.codium#sdks one of the examples is the GO SDK

**Comment by grisu48** [comment]
Thanks! Closing issue as this seems to be solved already.
