### ISSUE TITLE
chrome sandbox demands setuid

### ISSUE THREAD

**Issue by eike-fokken** [flathub/com.vscodium.codium#50]
Hi there,

when I run

```sh
 flatpak run com.vscodium.codium --verbose --log debug                 
```
I get the error:

```sh
[18:0722/121624.826402:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/share/codium/chrome-sandbox is owned by root and has mode 4755.
```
Do you think it is reasonable to run instead

```sh
flatpak run com.vscodium.codium --verbose --log debug --no-sandbox
```
(disabling the electron sandbox) because I configured the flatpak sandbox to only allow access to specific directories and hence the rest of my system is off-limits to codium anyway (or so I hope).

For the broader issue: Is there a way to fake the suid on the sandbox in question?
Note: I guess the problem might only have surfaced because I installed codium without root (no sudo on the flatpak install command) as on another machine I don't have this problem.

**Comment by noonsleeper** [comment]
Hi @eike-fokken Yes, in the recent updates the --no-sandbox comes in the .desktop file. You need to add this parameter when you run codium from the cli, I don't know if you can fake that but electron complain if you try to runs it without uid 0 then suggest that runs with --no-sandbox.
I don't think that install this on system wide or user mode change anything, you still need to add `--no-sandbox` on the cli

https://github.com/flathub/com.vscodium.codium#run-flatpak-codium-from-host-terminal

**Comment by eike-fokken** [comment]
ok, so my solution is also the default solution. Thank you!

**Comment by yump** [comment]
FWIW, [com.visualstudio.code](https://github.com/flathub/com.visualstudio.code/pull/237) and [com.visualstudio.code-oss](https://github.com/flathub/com.visualstudio.code-oss/tree/zypak) are working on solutions with [Zypak](https://github.com/refi64/zypak).  (I don't know much about flatpak or anything about Zypak; just sharing information that turned up in the course of researching this problem.)
