### ISSUE TITLE
App is not openning via terminal

### ISSUE THREAD

**Issue by jeffteixeira** [flathub/com.vscodium.codium#52]
![image](https://user-images.githubusercontent.com/58240722/129130880-862642ec-f96d-44c8-8fad-b1d231778491.png)

**Comment by jeffteixeira** [comment]
It's openning with `--no-sandbox` option
![image](https://user-images.githubusercontent.com/58240722/129131114-aab42dad-7c24-4b57-8bb1-0108f52ae8db.png)
![image](https://user-images.githubusercontent.com/58240722/129131030-2c382f7e-bb40-4e21-bf23-4ae6f90d182f.png)

**Comment by noonsleeper** [comment]
Hi @jeffteixeira, this is explained in https://github.com/flathub/com.vscodium.codium#run-flatpak-codium-from-host-terminal

**Comment by noonsleeper** [comment]
@jeffteixeira, I'll close this ticket but you can track this issue [here](https://github.com/flathub/com.vscodium.codium/issues/55)
