### ISSUE TITLE
How are you expected to change the .desktop file to (always) launch with SDKs?

### ISSUE THREAD

**Issue by rugk** [flathub/com.vscodium.codium#56]
I read [your FAQ/Readme](https://github.com/flathub/com.vscodium.codium#sdks) on how to add SDKs and everything was quite easy except of adjusting the `.desktop` file to actually always launch with my extension:

```
$ flatpak install org.freedesktop.Sdk.Extension.node14
```

This works:
```
$ FLATPAK_ENABLE_SDK_EXT=node14 flatpak run com.vscodium.codium --no-sandbox
codium-wrapper: Evaluating /usr/lib/sdk/node14/enable.sh
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
```

But you usually do not want to launch the stuff from the CLI, so after [looking again where these pesky `.desktop` files are found](https://github.com/flatpak/flatpak/issues/1286#issuecomment-354554684) I could edit the file there (with root permissions, unfortunately), but obviously not really correctly.

So let's edit that with `nano`:
```
  GNU nano 5.8                                  com.vscodium.codium.desktop                                             
[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=FLATPAK_ENABLE_SDK_EXT=node14 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/codium --file->
Icon=com.vscodium.codium
Type=Application
StartupNotify=false
StartupWMClass=VSCodium
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-codium-workspace;
Actions=new-empty-window;
Keywords=vscode;
X-Flatpak=com.vscodium.codium

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=FLATPAK_ENABLE_SDK_EXT=node14 /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/codium --file->
Icon=com.vscodium.codium
```

That did not work…

My goal is just to have npm/nodejs there in/as my dev environment…

**Comment by noonsleeper** [comment]
Hi @rugk, Sorry for the late response. I had a bit busy IRL =( (recently I only applied the changes of version)

Do you try to add this env var with [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) or adding double quotes to the SDK name?

for user
```
$ flatpak override --user  com.vscodium.codium --env=FLATPAK_ENABLE_SDK_EXT="nodejs14"
```

for system-wide
```
$ flatpak override com.vscodium.codium --env=FLATPAK_ENABLE_SDK_EXT="nodejs14"
```

**Comment by rugk** [comment]
Uhm I thought I had a similar issue open somewhere (the other VS Code fork maybe?), and in the end it was an issue that I was using `nodejs14` instead of `node14` as I was expected to do and I guess you just copied my wrong example… :see_no_evil: 

I'm sorry for this little devil-lish issue.

**Comment by noonsleeper** [comment]
no problem @rugk =)
