### ISSUE TITLE
Flatpak SDK question

### ISSUE THREAD

**Issue by goldcoders** [flathub/com.vscodium.codium#6]
Hi I have an archlinux set up
Pretty much i have all installed on my machine
for example node php ...

My question is What does Installing 
flatpak install flathub org.freedesktop.Sdk.Extension.php74
do?
if i checked my integrated terminal i still have my php locally installed by my package manager.

Can you give me a good example or usecase for flatpak sdk...
and where would i put this code
FLATPAK_ENABLE_SDK=php74,node12 flatpak run com.vscodium.codium

seems like when i add it on my profile or zshrc 
when i open a termnial it just launches the vscodium instantly
i guess my usage is incorrect

or do i need to just type it on the terminal coz it just launch a new instance of vscodium, and what would that benefit me using the sdk...

hope you can answer this thanks

**Comment by noonsleeper** [comment]
Hi

> flatpak install flathub org.freedesktop.Sdk.Extension.php74
> do?

This download the flatpak that contain php 7.4 to be used by as companion for any other flatpak.

> if i checked my integrated terminal i still have my php locally installed by my package manager.

If you change the integrated terminal to use your the host system's shell, the host shell is outside of flatpak and cannot acces to the content of flatpak SDK.

> Can you give me a good example or usecase for flatpak sdk...

As for any other flatpak package Isolate the installation of apps to be more distro agnostic, secure, etc and for sdks specifically add the possibility of extend functionality for other packages

> and where would i put this code
> FLATPAK_ENABLE_SDK=php74,node12 flatpak run com.vscodium.codium
> 
> seems like when i add it on my profile or zshrc
> when i open a termnial it just launches the vscodium instantly
> i guess my usage is incorrect

This command is intended for manually launch, maybe you need to add FLATPAK_ENABLE_SDK on your ~/.bashrc or ~/.zshrc in this way:

``` 
export FLATPAK_ENABLE_SDK=php74,node12
```

And then these sdks will be available not only for `flatpak run com.vscodium.codium` on your terminal but to all your session (for example to launch from menu)

I hope this help you.

**Comment by JeffTeixeira** [comment]
The version of gcc and python that comes by default are out of date. Is there a way to resolve this?

**Comment by noonsleeper** [comment]
@JeffTeixeira I assume if you try to install [pyenv](https://github.com/pyenv/pyenv-installer) inside of VSCodium container could work
```bash
flatpak run --command=bash com.vscodium.codium
```
and then
```bash
curl https://pyenv.run | bash
```
But I don't know if this could work well =( 

I prefer use the host shell like [this](https://github.com/flathub/com.vscodium.codium#host-shell)

**Comment by noonsleeper** [comment]
Hi @goldcoders I will close this issue due to a long period of non response. If you still having problems with, please open a new ticket. =)

And @JeffTeixeira don't hesitate and open a new ticket too
