### ISSUE TITLE
App doesn't open from Gnome Software

### ISSUE THREAD

**Issue by haluzpav** [flathub/com.vscodium.codium#64]
When I install VSCodium from Gnome Software, and then click Launch, nothing happens, it doesn't open. I'm on Fedora 34.

<img src="https://user-images.githubusercontent.com/24211726/139693485-227ced5f-8aa8-4743-a460-1d4be58804a6.png" width=200 /> <img src="https://user-images.githubusercontent.com/24211726/139693492-a1fe07c9-ef1b-422f-bcc8-e4e28e1d06f6.png" width=200 /> <img src="https://user-images.githubusercontent.com/24211726/139693497-18a7dbe5-c936-49e1-ad24-71afc44eed0b.png" width=200 />

I presume it's because it doesn't use `--no-sandbox` option, after seeing #52.

`flatpak run com.vscodium.codium --verbose` gives me

```
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
[18:1101/161244.267536:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/share/codium/chrome-sandbox is owned by root and has mode 4755.
```

Launching by shortcut in applications, or by `flatpak run com.vscodium.codium --no-sandbox` works fine.

**Comment by noonsleeper** [comment]
Hi @haluzpav, Currently the sandbox mode is disabled on upstream, we have an [issue to resolve this problem](https://github.com/flathub/com.vscodium.codium/issues/55). I will close this issue on favor of track the problem on the before mentioned.
