### ISSUE TITLE
VSCodium uses default font and theme for GTK3 vidgets

### ISSUE THREAD

**Issue by eternal-sorrow** [flathub/com.vscodium.codium#7]
GTK3 widgets in VSCodium interface (menubar and menus, file selection dialogs) use the default theme and font (Adwaita and Cantarell to be precise), even though I use another font and theme for my apps. Other flatpak apps don't have this problem (they use my system theme and fonts). Also, VSCodium does not seem to use xdg-desktop-portal for file dialogs.

Screenshot fragment illustrates theme and font difference between VSCodium file dialog (on the right) and non-flatpak GTK3 application (nautilus).
![2020-06-05-020747](https://user-images.githubusercontent.com/4847726/83781189-b1a93280-a67d-11ea-8cf3-912a9827af8e.png)

**Comment by noonsleeper** [comment]
Hi vscode flatpak does the same?

**Comment by eternal-sorrow** [comment]
I don't know about vscode, but code-oss does the same, yes.

**Comment by bilelmoussaoui** [comment]
Electron apps are not using the file chooser portal. For your theme to work properly with this case, you will have to have it installed as a flatpak as well.

**Comment by noonsleeper** [comment]
Thanks @bilelmoussaoui

**Comment by noonsleeper** [comment]
Hi @eternal-sorrow I will close this issue due to a long period of non response. If you still having problems with, please don't hesitate to open a new ticket. =)
