### ISSUE TITLE
How can I get codium to see flatpak openjdk11?

### ISSUE THREAD

**Issue by geekley** [flathub/com.vscodium.codium#72]
I'm having trouble getting flatpak codium to access java from flatpak's `org.freedesktop.Sdk.Extension.openjdk11`.

The README says you can do something like:
```sh
FLATPAK_ENABLE_SDK_EXT=dotnet,golang flatpak run com.vscodium.codium
```
So I tried: `FLATPAK_ENABLE_SDK_EXT=openjdk11 flatpak run ...` and pretty much every possible variation (java, jvm, org.freedesktop.Sdk.Extension.openjdk11, etc) but it always shows an error like:
```
codium-wrapper: Requested SDK extension "openjdk11" is not installed
```
And indeed I can't get `java -version` to run on a (non-host) terminal inside codium, and `ls /usr/lib/sdk` is empty.
I also tried this, but not even that works:
```sh
$ /run/host/usr/lib/jvm/default-java/bin/java -version
/run/host/usr/lib/jvm/default-java/bin/java: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/host/usr/lib/jvm/default-java/bin/java)
/run/host/usr/lib/jvm/default-java/bin/java: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/host/usr/lib/jvm/java-11-openjdk-amd64/bin/../lib/jli/libjli.so)
```

Maybe there's some flatpak override or similar which I can set?
I want use this specific version (flatpak's openjdk), not some custom additional installation of java on home or anything like that.

**Comment by noonsleeper** [comment]
@geekley I test like this
`flatpak install org.freedesktop.Sdk.Extension.openjdk11`
then
`FLATPAK_ENABLE_SDK_EXT=openjdk11 flatpak run com.vscodium.codium --no-sandbox`

![image](https://user-images.githubusercontent.com/62183384/145755677-56bc0756-d0b3-4072-9502-f597b9202d70.png)

Can you try in this way?

**Comment by geekley** [comment]
I did try that, but it didn't work ... I just tried it again:
`flatpak list` shows it's installed:
```
VSCodium                                com.vscodium.codium                       1.63.0       stable      system
[...]
OpenJDK 11 SDK Extension                org.freedesktop.Sdk.Extension.openjdk11                20.08       system
```
```sh
$ flatpak override --show com.vscodium.codium 
[Environment]
FLATPAK_ENABLE_SDK_EXT=*
$ FLATPAK_ENABLE_SDK_EXT=openjdk11 flatpak run com.vscodium.codium --no-sandbox
codium-wrapper: Adding /usr/lib/sdk/mono6/lib/pkgconfig to PKG_CONFIG_PATH
codium-wrapper: Adding /usr/lib/sdk/mono6/bin to PATH
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
```
On sandboxed terminal `java -version` doesn't work:
```
$ which java
which: no java in (/app/bin:/usr/bin:/usr/lib/sdk/mono6/bin:/home/me/.var/app/com.vscodium.codium/data/node/bin:/home/me/.var/app/com.vscodium.codium/data/cargo/bin:/home/me/.var/app/com.vscodium.codium/data/python/bin)
```

**Comment by noonsleeper** [comment]
you have the 20.08 version of the openjdk11 SDK and codium is using version 21.08, try to use that version.


> Could it be because my $JAVA_HOME isn't set outside flatpak? Though probably not, that doesn't make sense anyways...

I don't have java at all outside of the flatpak.

**Comment by geekley** [comment]
Thanks a lot, @noonsleeper ! That worked!

If you don't mind, can I make a suggestion, then? You could add this info to the README. For example, something like this:
`/app/share/ide-flatpak-wrapper/README.md`
```markdown
[...]
### SDKs
[...]
To get support for additional languages, you have to install SDK extensions, e.g.
[...]
If you have issues finding the SDK in the sandbox, make sure the version is compatible with 21.08.
You can use [...]
```
Where `21.08` is always replaced with whatever version codium is using (since it's not super obvious from a `flatpak list`).

**Comment by geekley** [comment]
You could also mention in README that it's possible to enable all available sdks with:
```sh
flatpak override --env='FLATPAK_ENABLE_SDK_EXT=*' com.vscodium.codium
```
Which is great because this way you don't have to edit the .desktop file.

**Comment by noonsleeper** [comment]
Hey @geekley, If you make a PR with this info will be good =)

**Comment by noonsleeper** [comment]
Hey @geekley, I'll close this since the issue was already solve.
