### ISSUE TITLE
Built-in git credential helper can't remember passwords

### ISSUE THREAD

**Issue by geekley** [flathub/com.vscodium.codium#73]
The Git (built-in) and Git Graph extensions can't remember the password entered into the prompt.
For example, if I click the sync button, it shows the prompt asking the password, and it works one time, but clicking it again triggers the prompt again. This shouldn't happen, since it should be saved somewhere.
It seems something is preventing it from being saved/loaded from gnome-keyring (or whatever the extension uses to store it) ...

I tried giving Codium the same permissions as IntelliJ Idea Community and restarting it:
```sh
sudo flatpak override --filesystem=xdg-run/keyring com.vscodium.codium
sudo flatpak override --talk-name=org.gnome.keyring.SystemPrompter com.vscodium.codium
```
But it didn't work. I'm still having the same problem.
When I enter `git fetch` on a flatpak-spawned terminal on host, it doesn't have this problem, as it doesn't use the credential manager from Code; it gets the password correctly from gnome-keyring.

But if I enter it on a sandboxed terminal (Code sets $GIT_ASKPASS) then I have the same problem.
Also, if I do `git help -a | grep credential-` on sandboxed terminal, it doesn't list `credential-libsecret` as one of the options available.

---
Codium v1.62.3

Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-22-generic (64-bit)
Graphics Platform: X11
```
gir1.2-secret-1/impish,now 0.20.4-2 amd64 [installed,automatic]
libsecret-1-0/impish,now 0.20.4-2 amd64 [installed,automatic]
libsecret-common/impish,impish,now 0.20.4-2 all [installed,automatic]
```

**Comment by noonsleeper** [comment]
I'll take a look on this

**Comment by noonsleeper** [comment]
hey @geekley you can provide a way to reproduce this. Something like an example will be good

**Comment by vchernin** [comment]
https://invent.kde.org/frameworks/kwallet/-/merge_requests/11

**Comment by noonsleeper** [comment]
hey @geekley, I'll close this old issue, if the problem persists please open a new issue.

**Comment by geekley** [comment]
Yeah, sorry for not replying. It's been a long time since I stopped using the flatpak version; I switched to snap.
So I don't know if it's happening or not. Just leave it closed :)
