### ISSUE TITLE
Crash at start with fedora 35

### ISSUE THREAD

**Issue by yodatak** [flathub/com.vscodium.codium#79]
Hi with visual coduim i got crash at start but not with offical visual studio code in flatpak 

 yodatak@localhost  ~  flatpak run com.visualstudio.code-oss -v
code-oss-wrapper: Setting up NPM packages
code-oss-wrapper: Setting up Cargo packages
code-oss-wrapper: Setting up Python packages
1.63.1
fe719cd3e5825bf14e14182fddeb88ee8daf044f
x64
 yodatak@localhost  ~  flatpak run com.vscodium.codium -v      
codium-wrapper: Setting up NPM packages
codium-wrapper: Setting up Cargo packages
codium-wrapper: Setting up Python packages
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
x64

**Comment by noonsleeper** [comment]
Hey @yodatak I think you need to add `--no-sandbox`

[see this](https://github.com/flathub/com.vscodium.codium/issues/64)

**Comment by noonsleeper** [comment]
@yodatak this is working out of the box now, then I'll close this issue.
