### ISSUE TITLE
Remove --filesystem=host Permissions

### ISSUE THREAD

**Issue by BeatLink** [flathub/com.vscodium.codium#81]
Would it be possible to remove the filesystem=host permissions and implement more granular filesystem access in its stead?

**Comment by noonsleeper** [comment]
Hey @BeatLink,

This topic is always open to debate, what you purpose?
You need to take in consideration things like:

 - the current level is more easy for new users (They don't need to learn how to override permissions on flatpak, to start using it)
 - modify a file on any part of his filesystems needs to be as easy like when you do the same with vim/vi/nano
 
Btw you can always override the default using the cli or flatseal to be more restrictive. I think I can add a little section on readme to explain how to change the default level to a more restrictive.

**Comment by BeatLink** [comment]
Thanks, I will use the overrides for my personal configuration

**Comment by RalfJung** [comment]
I feel like this should at least be documented more prominently. The entire reason for using flatpak for me is to be sure that applications cannot access my secret keys even if they try, so seeing this permission as quite a shock.

The readme also contains statements like
> This version is running inside a container and is therefore not able to access SDKs on your host system!

which are misleading given the `--filesystem=host` -- they seem to promise a level of isolation that is not actually provided.

**Comment by noonsleeper** [comment]
@RalfJung If you need to discuss it, please make a new issue.
