### ISSUE TITLE
Terminal profiles aren't working, so I can't flatpak-spawn a non-sandboxed shell

### ISSUE THREAD

**Issue by geekley** [flathub/com.vscodium.codium#84]
It seems it stopped working after an update. Now I can only open a sandboxed terminal.
When I click "select default profile" no options are shown.

Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-04T06:27:19.879Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic -- Kubuntu 21.10

My settings:
```jsonc
"terminal.integrated.defaultProfile.linux": "bash",
"terminal.integrated.profiles.linux": {
  "bash": {
    "overrideName": true,
    "title": "Bash",
    "path": "/usr/bin/flatpak-spawn",
    "args": ["--host", "--env=TERM=xterm-256color", "bash"],
  },
  "flatpak-bash": {
    "id": "flatpak-bash",
    "extensionIdentifier": "",
    "overrideName": true,
    "title": "Flatpak Bash",
    "icon": "shield",
    "path": "/usr/bin/bash",
    "args": [],
  }
},
```

**Comment by GeoffreyCoulaud** [comment]
I can confirm this issue is real. It happens on my machine too.

settings : 
```json
    "terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "/usr/bin/flatpak-spawn",
            "args": ["--host", "--env=TERM=xterm-256color", "bash"]
        },
        "zsh": {
            "path": "/usr/bin/flatpak-spawn",
            "args": ["--host", "zsh"]
        }
    },
```

I'm on Manjaro gnome unstable, but this should not matter as it's a Flatpak.

**Comment by noonsleeper** [comment]
I tried this on flatpak's `code-oss` and also in a vm with ubuntu 20.04 I installed vscodium and vscode(propietary)
 from deb packages and I see the same error from latest version 1.64.2 
![image](https://user-images.githubusercontent.com/62183384/153678217-73f69dbb-9e95-4fd2-ab73-1ee334557b48.png)

Not only only this wrong behavior also, if you try to override one of the default profiles it disappear from the list and if the profile that you override is selected as default then the default is set as null.

Then I think is a problem on upstream that affect to all the compilations not only to vscodium.

**Comment by noverby** [comment]
This error in the newest version might be relevant:

```
[2022-02-14 08:34:42.024] [renderer1] [error] ENOENT: no such file or directory, open '/etc/shells': Error: ENOENT: no such file or directory, open '/etc/shells'
```

**Comment by noonsleeper** [comment]
Hey people, @gasinvein fixed this problem with a workaround on [ide-flatpak-wrapper](https://github.com/flathub/ide-flatpak-wrapper), go and say thanks for the effort =)
