### ISSUE TITLE
Debugging C code does not work when terminal is outside of container.

### ISSUE THREAD

**Issue by Aaron-Uriel** [flathub/com.vscodium.codium#96]
Hi, I'm using Fedora Silverblue and was trying to make a C project using VSCodium.
But when I tried to debug my project, I encountered this error 
![image](https://user-images.githubusercontent.com/40283192/166008813-410ee328-3055-487b-b1fa-58cd77e387f5.png)
It looks like it's trying to find those temporary files on the host `/tmp` and not in the container `/tmp`, and I found that the real location of the file is in `/run/user/1000/.flatpak/com.vscodium.codium/tmp/`
I think I can just debug my project using the terminal that is inside the container, and it seems that it would work but my executable requires a different version of GLIBC to run, and I can't compile it inside the container because it needs to use `-lncursesw` to work.
This is my terminal integrated profile:
```
"terminal.integrated.profiles.linux": {

        "bash": {
            "path": "/usr/bin/flatpak-spawn",
            "args": ["--host", "--env=TERM=xterm-256color", "bash"]
        },
        "Flatpak Escape": {
            "path": "flatpak-spawn",
            "args": [
                "--host",
                "toolbox",
                "run",
                "fish"
            ],
        }
    },
    "terminal.integrated.defaultProfile.linux": "Flatpak Escape",
```
And this is my gdb launch task:
```
{
        "name": "(gdb) Iniciar",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceRoot}/a.out",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${fileDirname}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "setupCommands": [
            {
                "description": "Habilitar la impresión con sangría para gdb",
                "text": "-enable-pretty-printing",
                "ignoreFailures": true
            },
            {
                "description":  "Establecer tipo de desensamblado en Intel",
                "text": "-gdb-set disassembly-flavor intel",
                "ignoreFailures": true
            }
        ]
}
```

I tried to debug much more simple single file program when using the containerized terminal and it worked perfectly (it does not use any external library).

**Comment by noonsleeper** [comment]
@Aaron-Uriel Sorry for the late response to this.

Maybe setting up this fix the problem with the container tmp directory

```
  "terminal.integrated.automationProfile.linux": {
    "path": "/usr/bin/flatpak-spawn",
    "args": ["--host", "--env=TERM=xterm-256color", "bash"],
    "overrideName": true
    },
```
this property control what is the terminal that codium/code use for internal tasks that is different of `"terminal.integrated.defaultProfile.linux"` that is the terminal that you see on the editor.

Could you please test this?

**Comment by noonsleeper** [comment]
Hey, I'll close this very old issue, if the problem persists, don't hesitate and open a new issue.
